/** Cross-category "People Also Used" suggestions */
export const alsoUsed: Record<string, string[]> = {
  "word-counter":          ["grammar-checker", "reading-time", "plagiarism-checker"],
  "grammar-checker":       ["word-counter", "plagiarism-checker", "ai-prompt-generator"],
  "plagiarism-checker":    ["grammar-checker", "word-counter", "text-diff"],
  "case-converter":        ["word-counter", "find-replace", "text-to-slug"],
  "lorem-ipsum":           ["markdown-preview", "word-counter", "reading-time"],
  "text-reverser":         ["case-converter", "word-counter", "find-replace"],
  "text-diff":             ["plagiarism-checker", "find-replace", "word-counter"],
  "markdown-preview":      ["word-counter", "reading-time", "grammar-checker"],
  "find-replace":          ["word-counter", "case-converter", "remove-extra-spaces"],
  "ai-prompt-generator":   ["grammar-checker", "word-counter", "reading-time"],

  "merge-pdf":             ["split-pdf", "compress-pdf", "pdf-to-image"],
  "split-pdf":             ["merge-pdf", "compress-pdf", "remove-pdf-pages"],
  "compress-pdf":          ["merge-pdf", "pdf-to-image", "compress-image"],
  "image-to-pdf":          ["merge-pdf", "compress-pdf", "resize-image"],
  "pdf-to-image":          ["image-to-pdf", "compress-image", "merge-pdf"],
  "rotate-pdf":            ["merge-pdf", "split-pdf", "compress-pdf"],
  "remove-pdf-pages":      ["split-pdf", "merge-pdf", "reorder-pdf"],
  "watermark-pdf":         ["sign-pdf", "compress-pdf", "merge-pdf"],
  "sign-pdf":              ["watermark-pdf", "compress-pdf", "lock-pdf"],
  "lock-pdf":              ["sign-pdf", "compress-pdf", "merge-pdf"],
  "unlock-pdf":            ["lock-pdf", "compress-pdf", "merge-pdf"],
  "edit-pdf":              ["sign-pdf", "watermark-pdf", "compress-pdf"],
  "page-numbers-pdf":      ["header-footer-pdf", "merge-pdf", "compress-pdf"],
  "reorder-pdf":           ["merge-pdf", "split-pdf", "remove-pdf-pages"],

  "compress-image":        ["resize-image", "convert-image", "image-cropper"],
  "resize-image":          ["compress-image", "convert-image", "image-cropper"],
  "convert-image":         ["compress-image", "resize-image", "image-to-base64"],
  "flip-image":            ["resize-image", "compress-image", "image-cropper"],
  "image-cropper":         ["resize-image", "compress-image", "watermark-image"],
  "watermark-image":       ["compress-image", "resize-image", "image-cropper"],
  "image-color-picker":    ["color-converter", "compress-image", "watermark-image"],
  "image-to-base64":       ["base64", "convert-image", "compress-image"],

  "bmi-calculator":        ["calorie-calculator", "water-intake", "ideal-weight"],
  "calorie-calculator":    ["bmi-calculator", "water-intake", "heart-rate-zones"],
  "water-intake":          ["bmi-calculator", "calorie-calculator", "sleep-calculator"],
  "sleep-calculator":      ["water-intake", "calorie-calculator", "bmi-calculator"],
  "age-calculator":        ["date-calculator", "bmi-calculator", "pregnancy-calculator"],
  "ideal-weight":          ["bmi-calculator", "calorie-calculator", "water-intake"],
  "pregnancy-calculator":  ["age-calculator", "water-intake", "bmi-calculator"],
  "heart-rate-zones":      ["bmi-calculator", "calorie-calculator", "ideal-weight"],

  "loan-calculator":       ["sip-calculator", "compound-interest", "tax-regime-calculator"],
  "sip-calculator":        ["loan-calculator", "compound-interest", "fd-calculator"],
  "compound-interest":     ["sip-calculator", "loan-calculator", "fd-calculator"],
  "currency-converter":    ["loan-calculator", "sip-calculator", "salary-calculator"],
  "tax-regime-calculator": ["loan-calculator", "salary-calculator", "sip-calculator"],
  "salary-calculator":     ["tax-regime-calculator", "loan-calculator", "sip-calculator"],
  "fd-calculator":         ["sip-calculator", "compound-interest", "loan-calculator"],
  "gst-calculator":        ["invoice-generator", "currency-converter", "salary-calculator"],
  "discount-calculator":   ["percentage-calculator", "gst-calculator", "tip-calculator"],

  "json-formatter":        ["base64", "url-encoder", "jwt-decoder"],
  "base64":                ["json-formatter", "url-encoder", "image-to-base64"],
  "url-encoder":           ["base64", "json-formatter", "html-entities"],
  "jwt-decoder":           ["json-formatter", "base64", "hash-generator"],
  "password-generator":    ["hash-generator", "base64", "uuid-generator"],
  "hash-generator":        ["password-generator", "base64", "uuid-generator"],
  "uuid-generator":        ["hash-generator", "password-generator", "json-formatter"],
  "regex-tester":          ["json-formatter", "find-replace", "text-diff"],
  "html-entities":         ["url-encoder", "base64", "json-formatter"],
  "css-minifier":          ["json-formatter", "base64", "url-encoder"],

  "color-converter":       ["image-color-picker", "compress-image", "markdown-preview"],
  "date-calculator":       ["age-calculator", "epoch-converter", "timezone-converter"],
  "epoch-converter":       ["date-calculator", "timezone-converter", "age-calculator"],
  "timezone-converter":    ["epoch-converter", "date-calculator", "pomodoro-timer"],

  "ats-score":             ["grammar-checker", "word-counter", "plagiarism-checker"],
  "qr-code-generator":     ["url-encoder", "invoice-generator", "password-generator"],
  "invoice-generator":     ["gst-calculator", "currency-converter", "salary-calculator"],
  "pomodoro-timer":        ["reading-time", "word-counter", "typing-speed-test"],
  "typing-speed-test":     ["word-counter", "reading-time", "pomodoro-timer"],
  "reading-time":          ["word-counter", "grammar-checker", "typing-speed-test"],
  "character-limit":       ["word-counter", "reading-time", "grammar-checker"],

  "word-to-pdf":           ["merge-pdf", "compress-pdf", "pdf-to-text"],
  "pdf-to-text":           ["word-to-pdf", "pdf-to-word", "merge-pdf"],
  "pdf-to-word":           ["pdf-to-text", "word-to-pdf", "compress-pdf"],
  "excel-to-csv":          ["csv-to-excel", "word-to-pdf", "json-formatter"],
  "csv-to-excel":          ["excel-to-csv", "word-to-pdf", "json-formatter"],

  "percentage-calculator": ["discount-calculator", "gst-calculator", "tip-calculator"],
  "tip-calculator":        ["percentage-calculator", "discount-calculator", "currency-converter"],
  "scientific-calculator": ["percentage-calculator", "discount-calculator", "gst-calculator"],
  "fuel-cost-calculator":  ["currency-converter", "percentage-calculator", "loan-calculator"],
  "roman-numeral":         ["scientific-calculator", "percentage-calculator", "number-base-converter"],
  "number-base-converter": ["roman-numeral", "hash-generator", "base64"],
  "readability-score":     ["word-counter", "reading-time", "grammar-checker"],
  "aspect-ratio":          ["resize-image", "image-cropper", "compress-image"],

  "length-converter":      ["weight-converter", "temperature-converter", "fuel-cost-calculator"],
  "temperature-converter": ["length-converter", "weight-converter", "calorie-calculator"],
  "weight-converter":      ["length-converter", "temperature-converter", "bmi-calculator"],

  "cgpa-calculator":          ["percentage-calculator", "gst-calculator", "age-calculator"],
  "loan-eligibility":         ["loan-calculator", "sip-calculator", "compound-interest"],
  "notice-period-calculator": ["date-calculator", "salary-calculator", "age-calculator"],
};
