export type FAQ = { q: string; a: string };
export const faqData: Record<string, FAQ[]> = {
  "word-counter": [
    { q: "Is this word counter free?", a: "Yes, completely free with no sign-up required. It works entirely in your browser." },
    { q: "Does it count characters with or without spaces?", a: "Both. The tool shows character count with spaces and without spaces simultaneously." },
    { q: "Can I use it for SEO meta descriptions?", a: "Yes. Meta descriptions should be under 160 characters. The character counter helps you stay within that limit." },
    { q: "Does my text get stored anywhere?", a: "No. Everything you type is processed locally in your browser and never sent to any server." },
  ],
  "grammar-checker": [
    { q: "Is this grammar checker free?", a: "Yes, entirely free with no account needed. It's powered by LanguageTool, the same open-source engine used by millions." },
    { q: "Which languages does it support?", a: "English (US, UK, AU) and auto-detect. More languages are supported by the underlying LanguageTool engine." },
    { q: "Is it better than Grammarly?", a: "For free usage, it checks grammar, spelling, punctuation, and style without any word limits or paywalls — making it a strong free alternative." },
    { q: "Does it save my text?", a: "No. Your text is sent only to the LanguageTool public API for checking and is not stored by PreppTools." },
  ],
  "plagiarism-checker": [
    { q: "How does this plagiarism checker work?", a: "It compares two texts using sentence-level similarity analysis and Jaccard similarity scoring to detect shared content." },
    { q: "Is it free?", a: "Yes, 100% free with no sign-up. It runs entirely in your browser." },
    { q: "Can it check against the internet?", a: "This tool compares two texts you provide. It's ideal for comparing a student submission against a source or checking for self-plagiarism." },
    { q: "What similarity score is considered plagiarism?", a: "Generally, above 30% similarity warrants review. Above 50% is considered high similarity. Context matters — some overlap is natural in academic fields." },
  ],
  "merge-pdf": [
    { q: "Is this PDF merger free?", a: "Yes, completely free with no file size limits imposed by PreppTools." },
    { q: "How many PDFs can I merge at once?", a: "You can merge multiple PDF files in a single operation. Simply add all files and arrange them in the order you want." },
    { q: "Is my PDF data private?", a: "Yes. PDF processing happens in your browser using PDF-lib. Your files are never uploaded to any server." },
    { q: "Can I reorder pages before merging?", a: "You can reorder the files before merging. For page-level reordering within a single PDF, use the Reorder PDF Pages tool." },
  ],
  "compress-pdf": [
    { q: "How much does PDF compression reduce file size?", a: "Reduction varies by content. PDFs with many images typically compress by 40–70%. Text-only PDFs see smaller reductions." },
    { q: "Will compression affect quality?", a: "The tool optimises internal streams and structure. For most documents the visual quality remains the same." },
    { q: "Is there a file size limit?", a: "No hard limit is imposed by PreppTools. Very large files may take longer to process depending on your device." },
    { q: "Is this free?", a: "Yes, completely free. No watermarks, no sign-up, no subscription required." },
  ],
  "bmi-calculator": [
    { q: "What is a healthy BMI range?", a: "According to WHO: Under 18.5 is underweight, 18.5–24.9 is normal, 25–29.9 is overweight, and 30 or above is obese." },
    { q: "Is BMI accurate?", a: "BMI is a useful screening tool but doesn't account for muscle mass, bone density, or fat distribution. Athletes may have high BMI despite low body fat." },
    { q: "Does this BMI calculator use metric or imperial?", a: "Both. You can enter height in cm or feet/inches, and weight in kg or pounds." },
    { q: "Is BMI different for children?", a: "Yes. For people under 18, BMI is interpreted using age and gender-specific growth charts, not the standard adult ranges." },
  ],
  "loan-calculator": [
    { q: "What is EMI?", a: "EMI (Equated Monthly Instalment) is the fixed monthly amount you pay to repay a loan, comprising both principal and interest." },
    { q: "How is EMI calculated?", a: "EMI = [P × r × (1+r)^n] / [(1+r)^n – 1], where P is the principal, r is the monthly interest rate, and n is the number of months." },
    { q: "Does prepayment reduce EMI or tenure?", a: "Most lenders offer both options. Reducing tenure saves more interest overall. This calculator shows the standard EMI without prepayment." },
    { q: "Is this free to use?", a: "Yes, completely free with no sign-up. Results are instant and all calculations happen in your browser." },
  ],
  "currency-converter": [
    { q: "Are the exchange rates live?", a: "Yes. Rates are fetched from a live exchange rate API and updated regularly throughout the day." },
    { q: "How many currencies are supported?", a: "30+ major world currencies including USD, EUR, GBP, INR, JPY, AED, SGD, and more." },
    { q: "Is this currency converter free?", a: "Yes, completely free with no account needed." },
    { q: "Can I convert INR to USD?", a: "Yes. Select INR as the source currency and USD as the target, enter the amount, and get the live converted value." },
  ],
  "tax-regime-calculator": [
    { q: "Which tax regime is better for me?", a: "It depends on your deductions. If you claim HRA, 80C, 80D and other deductions totalling more than ₹3.75 lakh, the old regime is usually better. Otherwise the new regime tends to save more tax." },
    { q: "What is the 87A rebate?", a: "Section 87A provides a tax rebate of up to ₹12,500 under the old regime (for income up to ₹5L) and up to ₹25,000 under the new regime (for income up to ₹12L)." },
    { q: "Does this calculator include cess?", a: "Yes. A 4% health and education cess is applied on the calculated tax in both regimes." },
    { q: "Is this for FY 2025-26?", a: "Yes, the slabs and rebates are updated for FY 2025-26 (AY 2026-27) as per the latest Union Budget." },
  ],
  "ats-score": [
    { q: "What is an ATS score?", a: "An ATS (Applicant Tracking System) score measures how well your resume matches a job description based on keyword alignment, formatting, and structure." },
    { q: "What score should I aim for?", a: "Aim for 70% or above. Most companies' ATS systems filter out resumes scoring below 60–70% before a human ever sees them." },
    { q: "Why does ATS matter?", a: "Over 95% of Fortune 500 companies use ATS software. If your resume doesn't pass the scan, it won't reach a recruiter regardless of your qualifications." },
    { q: "Is this tool free?", a: "Yes, completely free. Upload your resume and paste any job description to get an instant compatibility score." },
  ],
  "password-generator": [
    { q: "Are the generated passwords stored anywhere?", a: "No. Passwords are generated entirely in your browser using the Web Crypto API and are never transmitted to any server." },
    { q: "What makes a strong password?", a: "A strong password is at least 12 characters long and includes a mix of uppercase, lowercase, numbers, and symbols. Avoid dictionary words and personal information." },
    { q: "Should I use a different password for every site?", a: "Absolutely. If one site is breached and you reuse passwords, all your accounts are at risk. Use a password manager to store unique passwords." },
    { q: "Is 16 characters enough?", a: "A random 16-character password would take billions of years to brute-force with current technology. Yes, it's more than enough." },
  ],
  "json-formatter": [
    { q: "What does JSON formatting do?", a: "It takes minified or messy JSON and adds proper indentation and line breaks, making it easy to read and debug." },
    { q: "Can it validate JSON?", a: "Yes. If your JSON has syntax errors (missing commas, unquoted keys, etc.) the formatter will highlight the error." },
    { q: "Is my JSON data private?", a: "Yes. All formatting happens in your browser. Your JSON is never sent to any server." },
    { q: "Can it minify JSON too?", a: "Yes. Minifying removes all whitespace to produce the smallest possible JSON string, ideal for APIs and storage." },
  ],
  "qr-code-generator": [
    { q: "What can I generate a QR code for?", a: "URLs, plain text, email addresses, phone numbers, SMS messages, and Wi-Fi credentials — all supported." },
    { q: "Can I download the QR code?", a: "Yes. Download as a PNG image suitable for print or digital use." },
    { q: "Do QR codes expire?", a: "Static QR codes (like the ones generated here) never expire. They always point to the URL or text you encoded." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the downloaded image." },
  ],
  "age-calculator": [
    { q: "How accurate is this age calculator?", a: "It calculates your exact age in years, months, days, hours, and minutes based on your date of birth and the current date and time." },
    { q: "Can I calculate the age between two specific dates?", a: "Yes. You can set any start and end date to find the exact duration between them." },
    { q: "Does it account for leap years?", a: "Yes, leap years are fully accounted for in the calculation." },
    { q: "Is this free?", a: "Yes, completely free. No sign-up required." },
  ],
  "sip-calculator": [
    { q: "What is SIP?", a: "SIP (Systematic Investment Plan) is a method of investing a fixed amount regularly (monthly) in a mutual fund. It benefits from rupee cost averaging and compounding." },
    { q: "What return rate should I use?", a: "Historical long-term average for equity mutual funds in India is around 12% annually. Use 10–12% for conservative estimates." },
    { q: "Is the return guaranteed?", a: "No. Mutual fund returns are market-linked and not guaranteed. The calculator shows estimates based on an assumed rate of return." },
    { q: "Is this calculator free?", a: "Yes, free to use with no sign-up required." },
  ],
  "ai-prompt-generator": [
    { q: "What AI platforms does this support?", a: "ChatGPT, Claude, Gemini, Midjourney, DALL·E, and Stable Diffusion — each with platform-specific optimisations." },
    { q: "Can I customise the tone and format?", a: "Yes. For text AI platforms you can select tone (professional, casual, friendly, etc.) and output format (bullet points, essay, table, etc.)." },
    { q: "Is this free?", a: "Yes, completely free with no API key or sign-up required." },
    { q: "What makes a good AI prompt?", a: "Be specific about context, format, tone, and length. The more details you provide, the better the AI output. This tool helps structure those details automatically." },
  ],
  "compress-image": [
    { q: "How much can images be compressed?", a: "JPEG images can typically be compressed by 50–80% with minimal visible quality loss. PNG files vary more depending on content." },
    { q: "Does compression affect image quality?", a: "The tool lets you control the quality level. Lower quality = smaller file. At 80% quality, most images are visually indistinguishable from the original." },
    { q: "Is my image uploaded to a server?", a: "No. Image compression runs entirely in your browser. Your images never leave your device." },
    { q: "What formats are supported?", a: "JPEG and PNG. For WebP conversion, use the Convert Image Format tool." },
  ],
  "invoice-generator": [
    { q: "Can I add my company logo?", a: "Yes, you can upload a logo and it will appear on the generated invoice PDF." },
    { q: "Is the invoice legally valid?", a: "The invoice contains all standard fields. However, legal requirements vary by country. Add your GST number and other statutory details as needed." },
    { q: "Can I save invoices for later?", a: "You can download each invoice as a PDF. For recurring invoices, save your template details and re-fill as needed." },
    { q: "Is this free?", a: "Yes, completely free. No watermark on the downloaded PDF and no subscription required." },
  ],
  "cgpa-calculator": [
    { q: "Which formula should I use?", a: "Most Indian universities follow the × 9.5 formula (Anna University, VTU, etc.). Check your university's handbook if unsure." },
    { q: "Is CGPA × 9.5 the standard in India?", a: "Yes, × 9.5 is the most common formula used across Indian universities on a 10-point CGPA scale. Some universities use × 10 or × 9." },
    { q: "How accurate is this calculator?", a: "The calculator uses the exact multiplier formula specified. Accuracy depends on which formula your university officially follows." },
    { q: "What do Distinction, First Class, etc. mean?", a: "Distinction is ≥ 75%, First Class is ≥ 60%, Second Class is ≥ 50%, and Pass is below that. These are standard Indian university grade classifications." },
    { q: "Is this free?", a: "Yes, 100% free with no sign-up required." },
  ],
  "loan-eligibility": [
    { q: "How is loan eligibility calculated?", a: "Banks generally allow an EMI of up to 50% of your net monthly income (called FOIR — Fixed Obligation to Income Ratio). This calculator uses that standard rule." },
    { q: "Does my credit score affect eligibility?", a: "Yes. A higher CIBIL score (750+) can get you better rates and higher eligibility. This calculator estimates based on income alone." },
    { q: "What is FOIR?", a: "FOIR (Fixed Obligation to Income Ratio) is the share of your income that goes to EMIs. Most banks cap this at 40–50% of gross monthly income." },
    { q: "Can I use this for home loans and personal loans?", a: "Yes, the formula applies to both. Home loans typically have lower rates and longer tenures, resulting in higher eligibility." },
    { q: "Is this free?", a: "Yes, completely free with no sign-up required." },
  ],
  "cover-letter-generator": [
    { q: "Does this cover letter generator use AI?", a: "It uses smart templates that adapt to your inputs — your name, role, company, skills, and achievement — to generate a personalised letter instantly, with no AI API costs or delays." },
    { q: "How do I personalise the cover letter further?", a: "After generating, add a specific line about why you want to work at that particular company — mention a product, mission, or recent news. This is the single biggest differentiator." },
    { q: "Which tone should I choose?", a: "Professional works for corporate roles (finance, law, consulting). Enthusiastic suits startups and creative companies. Confident is great for senior roles. Concise is best for tech companies that value brevity." },
    { q: "Is this free?", a: "Yes, completely free with no sign-up, no watermark, and no limit on how many letters you generate." },
  ],
  "notice-period-calculator": [
    { q: "How do I calculate my last working day?", a: "Add your notice period (in days) to your resignation date. The result is your last working day. This tool does that calculation instantly." },
    { q: "Are weekends counted in the notice period?", a: "In most cases yes — notice periods are in calendar days, not working days. Check your contract or HR policy to confirm." },
    { q: "What is notice buyout?", a: "Notice buyout means you pay your employer the equivalent of your salary for the unserved notice days. The cost is usually calculated as (Monthly Salary ÷ 30) × remaining days." },
    { q: "Can I negotiate a shorter notice period?", a: "Yes, if your employer agrees. This is common when you have a joining deadline at your new company. Get it in writing." },
    { q: "Is this free?", a: "Yes, free to use with no sign-up required." },
  ],
  "case-converter": [
    { q: "What is Title Case?", a: "Title Case capitalises the first letter of every major word, following standard English headline rules. It's used for headings, titles, and book names." },
    { q: "What is camelCase used for?", a: "camelCase joins words without spaces and capitalises each word after the first — e.g. myVariableName. It's the standard naming convention in JavaScript, Java, and many other languages." },
    { q: "What is the difference between snake_case and kebab-case?", a: "Both use lowercase words separated by a delimiter. snake_case uses underscores (used in Python and databases), while kebab-case uses hyphens (used in URLs and CSS class names)." },
    { q: "Is this case converter free?", a: "Yes, completely free with no sign-up. Paste your text and convert it instantly in any browser." },
  ],
  "text-reverser": [
    { q: "What does reversing text mean?", a: "Reversing text flips the order of all characters — so 'Hello' becomes 'olleH'. You can also reverse word order (each word stays intact but the sentence order flips) or reverse each line independently." },
    { q: "Why would I need to reverse text?", a: "Common uses include creating mirror text for artistic effects, testing string manipulation algorithms, encoding simple messages, and generating fun social media posts." },
    { q: "Does it reverse Unicode and emoji characters?", a: "Yes, the reverser handles Unicode characters including accented letters, Cyrillic, Arabic, and most emoji sequences correctly." },
    { q: "Is this free?", a: "Yes, completely free. No sign-up, no download required." },
  ],
  "lorem-ipsum": [
    { q: "What is Lorem Ipsum?", a: "Lorem Ipsum is placeholder text derived from a Latin work by Cicero (45 BC). It has been used in printing since the 1500s and is the standard dummy text for design and typesetting." },
    { q: "Why use Lorem Ipsum instead of real text?", a: "Placeholder text prevents readers and clients from being distracted by the content during design reviews, keeping focus on layout, fonts, and spacing rather than the words." },
    { q: "Can I generate it in different lengths?", a: "Yes. Choose the number of paragraphs, sentences, or words. The generator can produce a single word up to multiple pages of Lorem Ipsum text." },
    { q: "Is this free?", a: "Yes, completely free and works entirely in your browser with no sign-up required." },
  ],
  "find-replace": [
    { q: "Can I replace text with case sensitivity?", a: "Yes. Enable the case-sensitive option to match exact casing. Without it, 'apple' will also match 'Apple' and 'APPLE'." },
    { q: "Does it support whole-word matching?", a: "Yes. Whole-word mode ensures that replacing 'cat' won't affect 'caterpillar' or 'concatenate' — only standalone occurrences are replaced." },
    { q: "How many replacements can it handle?", a: "There is no practical limit. The tool can handle large blocks of text with thousands of replacements in a single operation." },
    { q: "Is this free?", a: "Yes, completely free and runs entirely in your browser without sending your text to any server." },
  ],
  "remove-duplicate-lines": [
    { q: "Does it preserve line order?", a: "Yes. By default, duplicate lines are removed while keeping the first occurrence and preserving the original order of the remaining lines." },
    { q: "Can I sort the output after deduplication?", a: "Yes. Enable the sort option to alphabetically sort all unique lines after removing duplicates — useful for keyword lists and glossaries." },
    { q: "Is it case-sensitive?", a: "Yes, by default. 'Apple' and 'apple' are treated as different lines. Enable case-insensitive mode to treat them as duplicates." },
    { q: "Is this free?", a: "Yes, completely free. Paste your list and get unique lines instantly." },
  ],
  "remove-extra-spaces": [
    { q: "What kinds of spaces does this tool remove?", a: "It removes double spaces between words, leading spaces at the start of lines, trailing spaces at the end of lines, and blank lines. It also handles non-breaking spaces (NBSP) common in copy-pasted web content." },
    { q: "Why does copy-pasted text often have extra spaces?", a: "PDFs, websites, and word processors insert hidden whitespace characters during formatting. These invisible characters cause problems when the text is imported into databases, emails, or coding environments." },
    { q: "Does it remove intentional line breaks?", a: "No. The tool preserves intentional single line breaks. Only consecutive blank lines are collapsed to a single blank line." },
    { q: "Is this free?", a: "Yes, completely free and processes everything in your browser." },
  ],
  "text-to-slug": [
    { q: "What is a URL slug?", a: "A slug is the last part of a URL that identifies a specific page — e.g., in 'prepptools.com/tools/word-counter', the slug is 'word-counter'. It's lowercase, uses hyphens instead of spaces, and contains no special characters." },
    { q: "Does it handle accented characters?", a: "Yes. Accented letters (é, ü, ñ, etc.) are transliterated to their ASCII equivalents (e, u, n) to ensure the slug is URL-safe." },
    { q: "Why are hyphens preferred over underscores in slugs?", a: "Google treats hyphens as word separators (like spaces) but treats underscores as part of a word. 'word-counter' ranks for 'word counter' searches; 'word_counter' does not." },
    { q: "Is this free?", a: "Yes, free to use instantly with no sign-up." },
  ],
  "markdown-preview": [
    { q: "What Markdown features are supported?", a: "Full CommonMark spec: headings (H1–H6), bold, italic, strikethrough, inline code, code blocks with syntax highlighting, ordered and unordered lists, blockquotes, horizontal rules, tables, and links." },
    { q: "Can I export to HTML?", a: "Yes. Copy the rendered HTML output from the preview panel to use in any web page, CMS, or email client." },
    { q: "Does it support GitHub Flavored Markdown (GFM)?", a: "Yes, including tables and task lists (- [x] checked item). GFM is the most commonly used Markdown variant for README files and documentation." },
    { q: "Is this free?", a: "Yes, completely free with no sign-up. Write and preview Markdown in real time." },
  ],
  "text-diff": [
    { q: "What does a diff tool do?", a: "A diff (difference) tool compares two text inputs side by side and highlights every addition, deletion, and modification between them, making it easy to see exactly what changed." },
    { q: "Is this useful for comparing code?", a: "Yes. Paste two versions of a function, config file, or JSON object to see which lines changed. For large codebases, use Git's built-in diff instead." },
    { q: "Can it compare entire documents?", a: "Yes. Paste full documents — no length limit is imposed by the tool. Processing is done entirely in your browser." },
    { q: "Is this free?", a: "Yes, completely free and private. Your text never leaves your browser." },
  ],
  "character-limit": [
    { q: "What platforms does this check for?", a: "Twitter/X (280), LinkedIn post (3,000), LinkedIn headline (220), Instagram caption (2,200), SMS (160), Google meta title (60), Google meta description (160), and YouTube title (100) — all shown simultaneously." },
    { q: "Why does Twitter allow 280 characters now?", a: "Twitter doubled the limit from 140 to 280 characters in 2017. However, tweets that are shorter tend to get more engagement, so most social media managers still aim for under 200." },
    { q: "How do emoji and special characters count?", a: "Most platforms count emoji as 2 characters (due to Unicode encoding). This tool matches that behavior for accurate platform-specific counts." },
    { q: "Is this free?", a: "Yes, completely free. Paste your text and see all platform limits at once." },
  ],
  "reading-time": [
    { q: "How is reading time calculated?", a: "The tool divides the word count by the average adult reading speed of 200–250 words per minute. Most blog posts are written for 200 WPM (comfortable reading pace)." },
    { q: "Why show reading time on blog posts?", a: "Articles with estimated reading times get 40% more readers on average. Knowing it takes 3 minutes to read reduces bounce rate because readers commit before starting." },
    { q: "What is the average reading speed?", a: "Adults read around 200–250 words per minute for general content. Technical content with code is read at around 100–150 WPM. Academic literature is read even slower, at 50–100 WPM." },
    { q: "Is this free?", a: "Yes, free to use instantly. Paste any text to get word count and reading time." },
  ],
  "readability-score": [
    { q: "What is the Flesch Reading Ease score?", a: "A score from 0–100. Higher is easier to read. Scores 60–70 are ideal for general audiences (like news articles). Below 30 is very difficult (academic papers, legal documents)." },
    { q: "What is the Flesch-Kincaid Grade Level?", a: "It estimates the US school grade level needed to understand the text. Grade 8 (13-year-old level) is the target for most web content and general business writing." },
    { q: "How can I improve readability?", a: "Use shorter sentences (aim for under 20 words each), prefer simple words over complex ones, use active voice, and break up long paragraphs. These changes reliably raise the Flesch score." },
    { q: "Is this free?", a: "Yes, completely free. Paste any text to get instant readability scores." },
  ],
  "typing-speed-test": [
    { q: "What is a good typing speed?", a: "Average is 40 WPM. Professionals target 65–80 WPM. Competitive typists exceed 100 WPM. Anything above 50 WPM puts you in the top half of all typists." },
    { q: "How is WPM calculated?", a: "WPM = (Total characters typed ÷ 5) ÷ time in minutes. Dividing by 5 normalizes for word length since 'a' and 'antidisestablishmentarianism' otherwise count unequally." },
    { q: "Does typing accuracy matter more than speed?", a: "Yes. At 90% accuracy your effective speed is lower than a slower typist at 99% accuracy. Focus on accuracy first — speed naturally follows with practice." },
    { q: "Is this free?", a: "Yes, completely free. Start typing immediately with no sign-up required." },
  ],
  "word-to-pdf": [
    { q: "Does the conversion preserve formatting?", a: "Basic formatting (headings, paragraphs, bold, italic) is preserved. Complex layouts with columns, tables, and images may not render perfectly, as the conversion happens client-side without a full Word rendering engine." },
    { q: "What file types are supported?", a: "The tool accepts .docx files (the modern Word format). Older .doc files are not supported. If you have a .doc file, open it in Word and save as .docx first." },
    { q: "Is my Word document private?", a: "Yes. The conversion happens entirely in your browser. Your document is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the PDF and no sign-up required." },
  ],
  "word-to-text": [
    { q: "What content is extracted?", a: "All body text from paragraphs, headings, and list items is extracted. Images, tables, headers, footers, and comments are stripped from the output." },
    { q: "Why would I extract plain text from a Word document?", a: "Common uses include importing content into CMS platforms, feeding text into AI tools or APIs, cleaning up formatting before editing, and archiving documents as plain text." },
    { q: "Is my document uploaded to a server?", a: "No. Extraction happens entirely in your browser using the Mammoth.js library. Your file never leaves your device." },
    { q: "Is this free?", a: "Yes, completely free with no file size limit imposed by PreppTools." },
  ],
  "percentage-calculator": [
    { q: "How do I calculate what percentage one number is of another?", a: "Divide the part by the whole and multiply by 100. E.g. 45 out of 60 = (45 ÷ 60) × 100 = 75%. This tool does that calculation instantly." },
    { q: "How do I find X% of a number?", a: "Multiply the number by the percentage and divide by 100. E.g. 20% of 350 = (20 × 350) ÷ 100 = 70. The percentage calculator handles all three variations." },
    { q: "How do I calculate percentage increase or decrease?", a: "Percentage change = ((New Value − Old Value) ÷ Old Value) × 100. A positive result is an increase; negative is a decrease. Enter both values and the tool computes it." },
    { q: "Is this free?", a: "Yes, completely free. All calculations happen instantly in your browser." },
  ],
  "roman-numeral": [
    { q: "What is the highest number in Roman numerals?", a: "The standard Roman numeral system goes up to 3,999 (MMMCMXCIX). Numbers above 3,999 require a vinculum (overline) notation, which is rarely used." },
    { q: "How do I read Roman numerals?", a: "Add symbols from left to right. When a smaller symbol appears before a larger one, subtract it instead. E.g. IV = 5 − 1 = 4, IX = 10 − 1 = 9, XL = 50 − 10 = 40." },
    { q: "Where are Roman numerals used today?", a: "Clock faces, movie sequels (Rocky IV), book chapters, Super Bowl numbers, copyright years (MMXXV = 2025), building inscriptions, and formal outlines." },
    { q: "Is this free?", a: "Yes, completely free with instant bidirectional conversion." },
  ],
  "scientific-calculator": [
    { q: "What functions does this calculator support?", a: "Trigonometric (sin, cos, tan, and their inverses), logarithmic (log base 10, natural log), square root, power, factorial, Pi (π), and Euler's number (e) — all standard scientific functions." },
    { q: "Does it support degrees and radians?", a: "Yes. Toggle between degree and radian mode for trigonometric calculations. Make sure you're in the correct mode for your calculation — sin(90°) = 1, but sin(90 radians) ≈ 0.894." },
    { q: "Can I use it for exam preparation?", a: "Yes. It matches the functionality of standard scientific calculators used in CBSE, JEE, and most competitive exams. Great for practising without a physical calculator." },
    { q: "Is this free?", a: "Yes, free to use instantly with no downloads or sign-up required." },
  ],
  "random-number": [
    { q: "Is the random number truly random?", a: "The tool uses the Web Crypto API's cryptographically secure random number generator (CSPRNG), which is significantly more random than Math.random() and suitable for security-sensitive uses." },
    { q: "Can I generate multiple numbers at once?", a: "Yes. Set the count to generate up to 100 random numbers in one click. Optionally require all numbers to be unique (no duplicates in the set)." },
    { q: "What is it used for?", a: "Common uses include lottery number selection, random sampling for research, giveaway winner selection, classroom activities, dice substitution in tabletop games, and generating test data." },
    { q: "Is this free?", a: "Yes, completely free with no limits on how many times you can generate numbers." },
  ],
  "coin-flip": [
    { q: "Is the coin flip fair?", a: "Yes. Each flip uses a cryptographically random 50/50 probability. There is no bias toward heads or tails regardless of previous results." },
    { q: "Can I flip multiple coins?", a: "Yes. Set the number of flips and the tool simulates all of them simultaneously and shows the results along with heads/tails counts." },
    { q: "Can I roll dice too?", a: "Yes. Switch to Dice Roller and choose to roll 1 to 6 dice. Each die shows an individual result with equal probability for all six faces." },
    { q: "Is this free?", a: "Yes, completely free and works instantly in any browser." },
  ],
  "aspect-ratio": [
    { q: "What is a 16:9 aspect ratio?", a: "16:9 is the standard widescreen ratio used by most monitors, TVs, YouTube videos, and presentations. For every 16 units of width, there are 9 units of height. Common resolutions include 1920×1080 and 3840×2160 (4K)." },
    { q: "What is the difference between 4:3 and 16:9?", a: "4:3 is the older standard-definition TV ratio (square-ish). 16:9 is the modern widescreen ratio. Content shot in 4:3 appears with black bars on the sides when viewed on a 16:9 screen." },
    { q: "How do I maintain aspect ratio when resizing?", a: "Enter a width and the tool calculates the correct height. Locking the ratio means if you change one dimension, the other adjusts proportionally to prevent stretching." },
    { q: "Is this free?", a: "Yes, completely free with instant calculation. No sign-up needed." },
  ],
  "number-base-converter": [
    { q: "What are the four common number bases?", a: "Binary (base 2, digits 0–1), Octal (base 8, digits 0–7), Decimal (base 10, digits 0–9), and Hexadecimal (base 16, digits 0–9 and A–F). All four conversions are shown simultaneously." },
    { q: "Why do programmers use hexadecimal?", a: "Hex is compact — each hex digit represents exactly 4 binary bits. Memory addresses, color codes (#FF5733), file hashes, and byte values are all naturally expressed in hexadecimal." },
    { q: "Why do computers use binary?", a: "Computers are built from transistors that have two states: on (1) or off (0). Binary directly maps to this physical reality. All other number systems are just human-readable representations of binary." },
    { q: "Is this free?", a: "Yes, completely free and converts all bases simultaneously as you type." },
  ],
  "color-converter": [
    { q: "What is the difference between HEX, RGB, and HSL?", a: "HEX (#FF5733) is a 6-character hexadecimal code used in CSS and design tools. RGB (255, 87, 51) represents red, green, and blue channel intensities. HSL (9°, 100%, 60%) uses Hue, Saturation, and Lightness — more intuitive for adjusting colors." },
    { q: "Which color format should I use in CSS?", a: "All three work in CSS. HEX is shortest and most commonly used. HSL is best when you want to adjust lightness or saturation programmatically. RGB is useful when you need to control opacity via rgba()." },
    { q: "What is CMYK used for?", a: "CMYK (Cyan, Magenta, Yellow, Key/Black) is used in print design. Printers mix ink in these four colors. RGB is for screens; CMYK is for print." },
    { q: "Is this free?", a: "Yes, free to use instantly with real-time conversion between all color formats." },
  ],
  "date-calculator": [
    { q: "What can I calculate with this date calculator?", a: "You can find the number of days, weeks, months, or years between two dates, add or subtract days from a date, find the day of the week for any date, and calculate date-based deadlines." },
    { q: "Does it account for leap years?", a: "Yes. All calculations correctly handle February 29 in leap years, so day counts and date arithmetic are always accurate." },
    { q: "How many days until a future date?", a: "Enter today's date as the start and your target date as the end. The calculator shows the exact number of days, weeks, and months until that date." },
    { q: "Is this free?", a: "Yes, completely free with instant calculations in your browser." },
  ],
  "compound-interest": [
    { q: "What is compound interest?", a: "Compound interest earns interest on both the principal and previously accumulated interest — unlike simple interest which only earns on the principal. Over time, this compounding effect dramatically accelerates growth." },
    { q: "How often does compounding matter?", a: "More frequent compounding (daily vs. annually) produces slightly higher returns. For most savings and investment calculations, annual compounding gives a good approximation." },
    { q: "What is the Rule of 72?", a: "Divide 72 by the annual interest rate to estimate how many years it takes for your money to double. At 8% annual return, your investment doubles in approximately 9 years (72 ÷ 8 = 9)." },
    { q: "Is this free?", a: "Yes, completely free. All calculations are instant and run in your browser." },
  ],
  "discount-calculator": [
    { q: "How do I calculate the final price after a discount?", a: "Multiply the original price by (1 − discount rate). For a 30% discount on ₹1,000: 1,000 × (1 − 0.30) = ₹700. This tool does that instantly." },
    { q: "How do I find the original price from a discounted price?", a: "Divide the sale price by (1 − discount rate). If you paid ₹700 after a 30% discount, the original price was 700 ÷ 0.70 = ₹1,000." },
    { q: "How do stacked discounts work?", a: "Stacked discounts (e.g. 20% off then 10% off) are not simply additive. First apply 20% to the original, then 10% to that result — equivalent to a ~28% total discount, not 30%." },
    { q: "Is this free?", a: "Yes, completely free. Works for any currency and any discount percentage." },
  ],
  "gst-calculator": [
    { q: "What are the GST slabs in India?", a: "India has four main GST slabs: 5% (essentials like food grains, healthcare), 12% (processed food, mobile phones), 18% (most goods and services), and 28% (luxury goods, vehicles, tobacco). Some items are exempt (0%)." },
    { q: "How do I add GST to a price?", a: "Multiply the base price by (1 + GST rate/100). For 18% GST on ₹1,000: 1,000 × 1.18 = ₹1,180 is the GST-inclusive price. The tool calculates this instantly." },
    { q: "How do I remove GST from an inclusive price?", a: "Divide the GST-inclusive price by (1 + GST rate/100). For ₹1,180 inclusive of 18% GST: 1,180 ÷ 1.18 = ₹1,000 is the base price before GST." },
    { q: "Is this free?", a: "Yes, completely free for all businesses and individuals in India." },
  ],
  "fuel-cost-calculator": [
    { q: "How is fuel cost calculated?", a: "Fuel cost = (Distance ÷ Fuel Efficiency) × Fuel Price. For a 300 km trip at 15 km/L efficiency with petrol at ₹105/L: (300 ÷ 15) × 105 = ₹2,100 total fuel cost." },
    { q: "What is a good fuel efficiency for a car?", a: "For petrol cars in India, 15–20 km/L is considered good. Diesel cars typically achieve 18–25 km/L. For highway trips, efficiency is usually 15–20% better than city driving." },
    { q: "Can I compare costs for two vehicles?", a: "Run the calculator twice — once for each vehicle — and compare the total costs. The difference shows exactly how much you save per trip by choosing the more fuel-efficient vehicle." },
    { q: "Is this free?", a: "Yes, completely free. Works for km/L and MPG with any fuel price." },
  ],
  "tip-calculator": [
    { q: "How do I split a bill evenly?", a: "Enter the total bill amount, choose the tip percentage, and set the number of people splitting. The calculator divides the total (bill + tip) equally and shows each person's share." },
    { q: "What is a standard tip percentage?", a: "In India, tipping 10% is common. In the US, 15–20% is standard for restaurants. For exceptional service, 20–25% is appropriate. The bill and tip percentage are entirely at your discretion." },
    { q: "Should I tip on the pre-tax or post-tax amount?", a: "Convention varies by country. In the US, most people tip on the pre-tax bill amount. In India, tipping on the total bill (including taxes) is typical." },
    { q: "Is this free?", a: "Yes, completely free. Works for any currency and any number of people." },
  ],
  "salary-calculator": [
    { q: "What is the difference between CTC and in-hand salary?", a: "CTC (Cost to Company) is the total amount a company spends on an employee annually, including PF, gratuity, and benefits. In-hand salary is what you actually receive in your bank account after all deductions." },
    { q: "What percentage of CTC do I actually take home?", a: "For most salaried employees in India, in-hand salary is approximately 70–80% of CTC, depending on the salary structure and applicable deductions like PF and professional tax." },
    { q: "What is HRA and can I exempt it from tax?", a: "HRA (House Rent Allowance) is a component of salary provided for housing costs. If you pay rent, you can claim HRA tax exemption under Section 10(13A) — one of the most valuable deductions for salaried employees." },
    { q: "Is this free?", a: "Yes, completely free and updated for the latest Indian tax slabs." },
  ],
  "fd-calculator": [
    { q: "What is the difference between FD and RD?", a: "A Fixed Deposit (FD) involves investing a lump sum at a fixed rate for a set tenure. A Recurring Deposit (RD) involves depositing a fixed amount every month. FDs suit those with a lump sum; RDs suit those building savings monthly." },
    { q: "Is FD interest taxable?", a: "Yes. FD interest is added to your total income and taxed at your applicable slab rate. Banks also deduct TDS (10%) if interest exceeds ₹40,000 per year (₹50,000 for senior citizens)." },
    { q: "Which bank has the best FD rates?", a: "Small finance banks and some private banks often offer the highest FD rates (up to 8–9% as of 2025). PSU banks offer lower but safer rates. Compare current rates before investing." },
    { q: "Is this free?", a: "Yes, completely free. Compare FD and RD maturity amounts instantly." },
  ],
  "calorie-calculator": [
    { q: "How are daily calorie needs calculated?", a: "The calculator uses the Mifflin-St Jeor equation to find your Basal Metabolic Rate (BMR) — the calories your body needs at rest — and multiplies it by an activity factor (1.2 to 1.9) based on your lifestyle." },
    { q: "How many calories should I eat to lose weight?", a: "A deficit of 500 calories per day leads to approximately 0.45 kg (1 lb) of weight loss per week. For safe, sustainable loss, aim for a deficit of 300–500 calories below your Total Daily Energy Expenditure (TDEE)." },
    { q: "What is BMR?", a: "BMR (Basal Metabolic Rate) is the number of calories your body burns just to maintain basic functions (breathing, circulation, organ function) at rest. It accounts for 60–70% of total calorie expenditure." },
    { q: "Is this free?", a: "Yes, completely free with support for both metric and imperial units." },
  ],
  "water-intake": [
    { q: "How much water should I drink per day?", a: "The standard recommendation is 30–35 ml per kg of body weight. A 70 kg person needs approximately 2.1–2.45 litres daily. The calculator personalizes this based on your weight and activity level." },
    { q: "Does drinking water help with weight loss?", a: "Yes. Drinking water before meals reduces appetite, and staying hydrated improves metabolism. Studies show that drinking 500 ml of water before meals can reduce calorie intake by 13%." },
    { q: "Does coffee count toward daily water intake?", a: "Moderate coffee (2–3 cups/day) counts toward hydration despite being a mild diuretic. Tea and other low-sugar beverages also count. Alcohol does not — it actively dehydrates." },
    { q: "Is this free?", a: "Yes, completely free with instant personalized hydration recommendations." },
  ],
  "sleep-calculator": [
    { q: "What is a sleep cycle?", a: "A complete sleep cycle lasts approximately 90 minutes and includes light sleep, deep sleep, and REM (Rapid Eye Movement) sleep. Adults need 4–6 complete cycles per night (6–9 hours total)." },
    { q: "Why do I feel groggy even after 8 hours of sleep?", a: "Waking during deep sleep (N3 stage) causes sleep inertia — grogginess that can last 30–60 minutes. The sleep calculator shows wake times that align with the end of a cycle, when you naturally sleep lightest." },
    { q: "How much sleep do adults actually need?", a: "The CDC recommends 7–9 hours per night for adults (18–64). Less than 6 hours consistently is linked to impaired cognition, weakened immunity, and increased cardiovascular risk." },
    { q: "Is this free?", a: "Yes, free to use with no sign-up. Enter your wake-up time to get optimal bedtimes." },
  ],
  "ideal-weight": [
    { q: "Which ideal weight formula is most accurate?", a: "No single formula is definitively most accurate — all are approximations. The Robinson formula is considered the most clinically balanced. BMI combined with waist circumference is a more complete health assessment." },
    { q: "Is BMI the same as ideal weight?", a: "No. BMI measures whether your current weight is proportional to your height. Ideal weight formulas calculate a specific target weight range. Both are screening tools, not diagnoses." },
    { q: "Can I be healthy above my ideal weight range?", a: "Yes. Athletes with high muscle mass often exceed ideal weight ranges while being very healthy. Body composition (fat vs. muscle percentage) matters more than weight alone." },
    { q: "Is this free?", a: "Yes, completely free with results in both kilograms and pounds." },
  ],
  "heart-rate-zones": [
    { q: "What are the five heart rate zones?", a: "Zone 1 (50–60% MHR): Very light recovery. Zone 2 (60–70%): Fat-burning, building aerobic base. Zone 3 (70–80%): Cardio/aerobic endurance. Zone 4 (80–90%): Lactate threshold, improving performance. Zone 5 (90–100%): Maximum effort sprints." },
    { q: "Which zone burns the most fat?", a: "Zone 2 (60–70% MHR) burns the highest percentage of calories from fat. However, higher intensity zones burn more total calories per minute — what matters most for fat loss is overall caloric deficit." },
    { q: "How do I measure my heart rate during exercise?", a: "Use a heart rate monitor, fitness watch (Fitbit, Apple Watch, Garmin), or chest strap for real-time monitoring. Manual measurement: count your pulse for 15 seconds and multiply by 4." },
    { q: "Is this free?", a: "Yes, completely free. Enter your age to get all five heart rate training zones instantly." },
  ],
  "pregnancy-calculator": [
    { q: "How is the due date calculated?", a: "The standard method (Naegele's Rule) adds 280 days (40 weeks) to the first day of your last menstrual period. This assumes a regular 28-day cycle and ovulation on day 14." },
    { q: "How accurate is the calculated due date?", a: "Only about 5% of babies are born on their exact due date. Most births occur within 2 weeks before or after. The due date is a central estimate, not a precise prediction." },
    { q: "What are the key pregnancy milestones?", a: "Week 4: Missed period, positive test. Week 8: Heartbeat detectable. Week 12: End of first trimester, miscarriage risk drops. Week 20: Anatomy scan, mid-pregnancy. Week 28: Third trimester begins. Week 37: Full term." },
    { q: "Is this free?", a: "Yes, completely free. Enter your last menstrual period date to see your due date and week-by-week timeline." },
  ],
  "length-converter": [
    { q: "What units can I convert between?", a: "Millimeters, centimeters, meters, kilometers, inches, feet, yards, and miles — all shown simultaneously when you enter any value in any unit." },
    { q: "How many inches are in a foot?", a: "12 inches = 1 foot. 3 feet = 1 yard. 1,760 yards = 1 mile. 1 inch = 2.54 centimeters exactly (defined)." },
    { q: "How do I convert cm to feet and inches?", a: "Divide centimeters by 30.48 to get feet. Take the decimal part and multiply by 12 to get inches. E.g. 175 cm = 5.74 feet = 5 feet 8.9 inches. The converter handles this automatically." },
    { q: "Is this free?", a: "Yes, completely free with instant multi-unit conversion." },
  ],
  "weight-converter": [
    { q: "What weight units does this convert between?", a: "Milligrams, grams, kilograms, metric tonnes, ounces, pounds, and US short tons — all shown simultaneously when you enter a value in any unit." },
    { q: "How many pounds are in a kilogram?", a: "1 kilogram = 2.20462 pounds. 1 pound = 0.453592 kg. For a quick mental estimate: multiply kg by 2.2 to get pounds." },
    { q: "How do I convert stones to kg?", a: "1 stone = 14 pounds = 6.35 kg. Multiply your weight in stones by 6.35 to get kilograms. E.g. 11 stone = 69.85 kg." },
    { q: "Is this free?", a: "Yes, completely free with instant multi-unit conversion." },
  ],
  "temperature-converter": [
    { q: "What is the formula to convert Celsius to Fahrenheit?", a: "°F = (°C × 9/5) + 32. E.g. 100°C = (100 × 1.8) + 32 = 212°F. The reverse: °C = (°F − 32) × 5/9." },
    { q: "What is Kelvin used for?", a: "Kelvin is the SI unit of temperature used in science and engineering. Absolute zero (0 K = −273.15°C) is the lowest possible temperature. Kelvin is used in chemistry, physics, and astronomy." },
    { q: "What is normal body temperature in Fahrenheit and Celsius?", a: "Normal body temperature is 37°C (98.6°F). A fever is generally considered above 38°C (100.4°F). These are averages — normal ranges vary between 36.1°C and 37.2°C (97°F–99°F)." },
    { q: "Is this free?", a: "Yes, completely free with instant conversion between Celsius, Fahrenheit, and Kelvin." },
  ],
  "timezone-converter": [
    { q: "Which time zones are supported?", a: "All major IANA time zones covering every continent and country — including IST (India), EST/EDT (US East), PST/PDT (US West), GMT/BST (UK), CET/CEST (Europe), JST (Japan), SGT (Singapore), AEST (Australia), and more." },
    { q: "How do I schedule a meeting across time zones?", a: "Enter the meeting time in your local timezone and select the timezone of the participant. The tool shows the corresponding time and indicates if it falls outside working hours (before 9 AM or after 6 PM)." },
    { q: "What is UTC and why is it used?", a: "UTC (Coordinated Universal Time) is the global time standard that all time zones are offset from. UTC+5:30 is IST (India). UTC−5 is EST (US East). Using UTC avoids daylight saving time confusion." },
    { q: "Is this free?", a: "Yes, completely free with instant conversion across all major time zones." },
  ],
  "epoch-converter": [
    { q: "What is a Unix timestamp?", a: "A Unix timestamp is the number of seconds that have elapsed since January 1, 1970, 00:00:00 UTC — known as the Unix epoch. It's used universally across programming languages and databases to represent moments in time." },
    { q: "What is the Year 2038 problem?", a: "32-bit systems store Unix timestamps as signed 32-bit integers, which overflow on January 19, 2038. Modern 64-bit systems won't have this problem. Most current software has already migrated to 64-bit timestamps." },
    { q: "Does the converter support milliseconds?", a: "Yes. JavaScript and many APIs use milliseconds (Unix timestamp × 1000). Toggle between seconds and milliseconds mode in the tool." },
    { q: "Is this free?", a: "Yes, completely free. Convert any Unix timestamp to a readable date instantly." },
  ],
  "url-encoder": [
    { q: "What characters need to be URL-encoded?", a: "Spaces become %20 (or +), & becomes %26, = becomes %3D, # becomes %23, and all non-ASCII characters are percent-encoded. RFC 3986 defines which characters are 'unreserved' and safe without encoding." },
    { q: "What is the difference between encodeURI and encodeURIComponent?", a: "encodeURI encodes a full URL and leaves structural characters like /, ?, &, and # intact. encodeURIComponent encodes everything including those characters — use it for encoding query parameter values." },
    { q: "Why does my URL break when it contains spaces?", a: "Spaces are not valid URL characters. Browsers may auto-encode them, but servers and APIs often reject them. Always encode spaces as %20 in URLs you construct programmatically." },
    { q: "Is this free?", a: "Yes, completely free. Encode and decode URLs instantly in your browser." },
  ],
  "html-entities": [
    { q: "What is the most important HTML entity to know?", a: "The five critical entities are: &lt; (<), &gt; (>), &amp; (&), &quot; (\"), and &apos; ('). These five characters have special meaning in HTML and must always be encoded in user-generated content to prevent XSS." },
    { q: "When should I encode HTML entities?", a: "Always encode user-provided content before rendering it in HTML. This prevents XSS (cross-site scripting) attacks where malicious users inject HTML or JavaScript into your page." },
    { q: "What is &nbsp;?", a: "&nbsp; is a non-breaking space — it looks like a space but prevents line breaks at that point. Commonly used in menus, currency values (€ 100), and table cells where you don't want text to wrap." },
    { q: "Is this free?", a: "Yes, completely free. Encode and decode HTML entities instantly in your browser." },
  ],
  "jwt-decoder": [
    { q: "What is a JWT?", a: "A JSON Web Token (JWT) is a compact, URL-safe token format used for authentication. It contains three base64-encoded sections: header (algorithm type), payload (claims/data), and signature (verification)." },
    { q: "Can this tool verify the JWT signature?", a: "No. Signature verification requires the secret key, which should never be shared client-side. This tool decodes the header and payload only — suitable for inspecting token contents during debugging." },
    { q: "What is the 'exp' claim in a JWT?", a: "'exp' is the expiration timestamp — a Unix timestamp after which the token is considered invalid. If your request is returning 401 Unauthorized, check if exp has passed. The decoder shows this as a human-readable date." },
    { q: "Is this free?", a: "Yes, completely free and processes everything in your browser. Your JWT never leaves your device." },
  ],
  "base64": [
    { q: "What is Base64 encoding?", a: "Base64 converts binary data into a string of 64 printable ASCII characters (A–Z, a–z, 0–9, +, /). This allows binary content like images and files to be safely transmitted in text-based protocols like HTTP headers, JSON, and email." },
    { q: "Does Base64 encrypt my data?", a: "No. Base64 is encoding, not encryption. Anyone can decode a Base64 string instantly. Never use Base64 to protect sensitive data — use proper encryption (AES, RSA) for that purpose." },
    { q: "Why is Base64 output longer than the original?", a: "Base64 encodes 3 bytes of input as 4 characters of output, making the result about 33% larger than the original. This is the tradeoff for making binary data text-safe." },
    { q: "Is this free?", a: "Yes, completely free and works entirely in your browser. Your data is never sent to any server." },
  ],
  "hash-generator": [
    { q: "What is the difference between MD5, SHA-1, and SHA-256?", a: "MD5 (128-bit) is fast but cryptographically broken — don't use it for security. SHA-1 (160-bit) is deprecated and vulnerable. SHA-256 (256-bit) is the current industry standard for secure hashing. Use SHA-256 or SHA-512 for passwords and file integrity." },
    { q: "Can I reverse a hash back to the original text?", a: "No. Hash functions are one-way — designed to be impossible to reverse. If you see your hash in a rainbow table attack lookup, that's why you should always add a salt before hashing passwords." },
    { q: "What is a hash used for?", a: "Password storage (always hashed, never plaintext), file integrity verification (SHA-256 checksums), digital signatures, data deduplication, and generating content fingerprints." },
    { q: "Is this free?", a: "Yes, completely free. All hashing happens in your browser using the Web Crypto API." },
  ],
  "uuid-generator": [
    { q: "What is a UUID?", a: "A UUID (Universally Unique Identifier) is a 128-bit identifier formatted as 8-4-4-4-12 hexadecimal characters (e.g. 550e8400-e29b-41d4-a716-446655440000). Version 4 UUIDs are randomly generated." },
    { q: "How unique is a UUID?", a: "Extremely unique. The probability of generating the same UUID twice is astronomically small — roughly 1 in 5.3 × 10^36. In practice, UUID collisions essentially never happen." },
    { q: "When should I use a UUID as a primary key?", a: "UUID primary keys are ideal for distributed systems where rows are created on multiple servers simultaneously and merged later, or when you don't want sequential IDs that expose your database size." },
    { q: "Is this free?", a: "Yes, completely free. Generate up to 100 UUIDs in one click." },
  ],
  "regex-tester": [
    { q: "What is a regular expression?", a: "A regex (regular expression) is a pattern used to match text. For example, \\d+ matches one or more digits, [A-Z] matches any uppercase letter, and ^hello matches strings that start with 'hello'." },
    { q: "What are common regex use cases?", a: "Validating email addresses, phone numbers, and passwords; extracting data from log files and HTML; find-and-replace in text editors; URL routing in web frameworks; form validation in JavaScript." },
    { q: "What flags are supported?", a: "g (global — find all matches), i (case-insensitive), m (multiline — ^ and $ match line starts/ends), s (dotAll — dot matches newlines), and u (Unicode mode)." },
    { q: "Is this free?", a: "Yes, completely free. Test regex patterns with live match highlighting in your browser." },
  ],
  "cron-builder": [
    { q: "What is a cron expression?", a: "A cron expression is a string of 5 fields (minute, hour, day-of-month, month, day-of-week) that defines when a scheduled task runs. '0 9 * * 1–5' means 'at 9:00 AM every weekday'." },
    { q: "What does * mean in a cron expression?", a: "An asterisk means 'every' for that field. '* * * * *' runs every minute. '0 * * * *' runs at the start of every hour. '0 0 * * *' runs at midnight every day." },
    { q: "Can I use this for GitHub Actions or AWS EventBridge?", a: "Yes. Both use cron syntax for scheduling. Note that AWS EventBridge uses 6 fields (adds seconds or year), while standard Unix cron uses 5. Copy the expression and paste it directly into your config." },
    { q: "Is this free?", a: "Yes, completely free. Build and validate cron expressions visually with a human-readable description." },
  ],
  "css-minifier": [
    { q: "How much does CSS minification reduce file size?", a: "Typically 20–40% depending on how much whitespace and how many comments your CSS contains. A 50 KB stylesheet can become 30–35 KB after minification, reducing load time measurably." },
    { q: "Does minification change how the CSS works?", a: "No. Minification only removes whitespace, comments, and redundant characters. The browser parses the minified CSS identically to the original — visual output is unchanged." },
    { q: "When should I use CSS minification?", a: "Always in production. Never manually edit minified CSS — always edit the source and minify before deploying. Use a build tool (Webpack, Vite, PostCSS) to automate this in CI/CD pipelines." },
    { q: "Is this free?", a: "Yes, completely free. Minify or beautify CSS instantly in your browser." },
  ],
  "ip-lookup": [
    { q: "What information does IP lookup show?", a: "Your public IP address, country, city, region, ISP (Internet Service Provider), organization, timezone, and approximate coordinates (latitude/longitude). This is the information any website can see when you visit it." },
    { q: "Why is my location wrong?", a: "IP geolocation is approximate — accurate to city or region level at best. ISPs assign IP blocks to cities but individual users in suburbs or rural areas may appear in a nearby city." },
    { q: "What is the difference between public and private IP?", a: "Your public IP is assigned by your ISP and visible on the internet. Private IPs (192.168.x.x, 10.x.x.x) are used within your local network. This tool shows your public IP — the one websites see." },
    { q: "Is this free?", a: "Yes, completely free. Your IP details are fetched and displayed instantly." },
  ],
  "image-color-picker": [
    { q: "What color formats does it output?", a: "HEX (e.g. #FF5733), RGB (e.g. rgb(255, 87, 51)), and HSL (e.g. hsl(9, 100%, 60%)). Copy any format with one click for use in CSS, design tools, or code." },
    { q: "How accurate is the color picker?", a: "It picks the exact pixel color at the cursor position from the uploaded image. On high-DPI (Retina) screens the accuracy is pixel-perfect." },
    { q: "Can I pick colors from a screenshot?", a: "Yes. Take a screenshot, save it as a PNG or JPG, and upload it to the color picker. This lets you extract colors from any UI, website, or app on your screen." },
    { q: "Is this free?", a: "Yes, completely free and works entirely in your browser. Your images are never uploaded to any server." },
  ],
  "image-cropper": [
    { q: "What aspect ratios are supported?", a: "Free crop (any ratio), 1:1 (square, for Instagram), 4:3 (standard photo), 16:9 (YouTube thumbnail, widescreen), 3:2 (DSLR photos), and custom pixel dimensions." },
    { q: "Does cropping reduce image quality?", a: "No. Cropping only removes pixels from the edges — it doesn't compress or re-encode the remaining image. Download as PNG to preserve full quality." },
    { q: "Can I crop to exact pixel dimensions?", a: "Yes. Enter the exact width and height in pixels for the crop area. Useful when preparing images for specific sizes like profile photos (400×400) or website banners." },
    { q: "Is this free?", a: "Yes, completely free. Your images are processed locally and never uploaded to a server." },
  ],
  "watermark-image": [
    { q: "Can I add a logo as a watermark instead of text?", a: "The current tool adds text watermarks. For logo watermarks, use image editing software like Canva, GIMP, or Photoshop where you can overlay a PNG logo with transparency." },
    { q: "What opacity level should I use for watermarks?", a: "30–50% opacity is standard for watermarks — visible enough to credit the creator but subtle enough not to obscure the image. Adjust based on image brightness and complexity." },
    { q: "Will the watermark prevent people from copying my image?", a: "Text watermarks deter casual copying and credit you when images are shared. A determined person can crop or remove them. For stronger protection, use a copyright registration." },
    { q: "Is this free?", a: "Yes, completely free. Add watermarks to your images instantly without Photoshop." },
  ],
  "image-to-base64": [
    { q: "What is a Base64 image data URI?", a: "A data URI is a URL scheme that embeds file content directly in the URL string: data:image/png;base64,iVBOR.... It lets you embed images in HTML and CSS without a separate file request." },
    { q: "When should I embed images as Base64?", a: "Use Base64 for small images like icons and logos (under 5 KB) where eliminating an HTTP request improves performance. For large images, Base64 is counterproductive — it increases file size by ~33% and can't be cached separately." },
    { q: "Can I use Base64 images in email templates?", a: "Yes. Many email clients block external images but render inline Base64 images. Embed logos and icons as Base64 data URIs in HTML emails for reliable display across all email clients." },
    { q: "Is this free?", a: "Yes, completely free. Your images are processed locally and never uploaded to any server." },
  ],
  "image-to-pdf": [
    { q: "What image formats can I convert to PDF?", a: "JPEG, PNG, WebP, and GIF are supported. Each image becomes one page in the PDF. You can add multiple images and they become consecutive pages." },
    { q: "Can I control the PDF page size?", a: "Yes. Choose from A4, Letter, or fit the PDF page to the image dimensions. For photographs, fitting to image preserves the original dimensions without scaling." },
    { q: "Is my image uploaded to a server?", a: "No. PDF creation happens entirely in your browser using PDF-lib. Your images never leave your device." },
    { q: "Is this free?", a: "Yes, completely free with no watermark and no file size limit imposed by PreppTools." },
  ],
  "convert-image": [
    { q: "What format should I convert to for websites?", a: "WebP is the best format for websites — it's 25–35% smaller than JPEG at the same quality and is supported by all modern browsers. Convert your JPEG or PNG images to WebP for better Core Web Vitals scores." },
    { q: "When should I use PNG vs JPEG?", a: "Use PNG for images with transparency, logos, and graphics with solid colors (lossless compression). Use JPEG for photographs and complex images (lossy but much smaller at similar quality)." },
    { q: "Does converting formats affect image quality?", a: "Converting from PNG to JPEG introduces slight lossy compression. Converting back from JPEG to PNG doesn't recover quality — it just stores the already-compressed pixels in a lossless container." },
    { q: "Is this free?", a: "Yes, completely free. All conversion happens in your browser with no server upload." },
  ],
  "resize-image": [
    { q: "What should I lock aspect ratio?", a: "Locking the aspect ratio ensures that when you change width, the height adjusts proportionally (and vice versa), preventing distorted, stretched images." },
    { q: "What are standard social media image sizes?", a: "Facebook post: 1200×628. Instagram square: 1080×1080. Instagram story: 1080×1920. Twitter post: 1600×900. LinkedIn banner: 1584×396. YouTube thumbnail: 1280×720." },
    { q: "Does resizing reduce image quality?", a: "Reducing size (downscaling) preserves quality well. Increasing size beyond the original dimensions (upscaling) degrades quality as pixels are interpolated — the image becomes blurry. Avoid upscaling if possible." },
    { q: "Is this free?", a: "Yes, completely free. Your images are processed locally with no server upload." },
  ],
  "flip-image": [
    { q: "What is the difference between flip and rotate?", a: "Flip mirrors the image along a vertical axis (horizontal flip — left becomes right) or horizontal axis (vertical flip — top becomes bottom). Rotate turns the image by 90, 180, or 270 degrees." },
    { q: "Why would I flip an image horizontally?", a: "Selfie cameras capture mirror images — the image looks correct to you but reversed to others. Flipping horizontally corrects this. It's also used for creating symmetrical compositions and correcting scanned documents that were placed face-down backwards." },
    { q: "Does flipping reduce image quality?", a: "No. Flipping is a lossless operation on pixel positions. Download as PNG to ensure zero quality loss." },
    { q: "Is this free?", a: "Yes, completely free and works instantly in your browser." },
  ],
  "split-pdf": [
    { q: "Can I split a PDF into individual pages?", a: "Yes. Choose 'Extract every page as a separate file' to split a PDF into one file per page, or specify a range (e.g. pages 5–12) to extract just those pages." },
    { q: "Can I remove specific pages when splitting?", a: "Yes. Enter the page numbers you want to keep, and the tool creates a new PDF with only those pages. This is also useful for removing specific pages from a document." },
    { q: "Is my PDF private?", a: "Yes. All splitting happens in your browser. Your PDF is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no file size limit imposed by PreppTools." },
  ],
  "rotate-pdf": [
    { q: "Can I rotate individual pages or all pages?", a: "Both. Choose to rotate all pages by the same amount, or specify individual pages to rotate at different angles (90°, 180°, 270° clockwise)." },
    { q: "Why would I need to rotate a PDF?", a: "Scanned documents often come out sideways or upside-down. Rotating fixes the orientation before sharing, printing, or archiving." },
    { q: "Is my PDF private?", a: "Yes. Rotation happens entirely in your browser. Your document is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the output." },
  ],
  "remove-pdf-pages": [
    { q: "How do I remove specific pages from a PDF?", a: "Enter the page numbers you want to delete (e.g. '3, 7, 12' or '5–9' for a range). The tool creates a new PDF with those pages removed and all other pages preserved." },
    { q: "Can I remove the last page of a PDF?", a: "Yes. Enter the last page number and it will be removed. If you're unsure of the page count, the tool shows the total after upload." },
    { q: "Is my PDF private?", a: "Yes. Page removal happens entirely in your browser using PDF-lib. Your file is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark and no file size limit." },
  ],
  "reorder-pdf": [
    { q: "How do I reorder PDF pages?", a: "Upload your PDF and drag the page thumbnails to rearrange them. The pages in the downloaded PDF will follow exactly the order you set." },
    { q: "Can I use this to move a page from the middle to the end?", a: "Yes. Drag any page thumbnail to any position. The tool gives you complete control over the final page order." },
    { q: "Is my PDF private?", a: "Yes. Reordering happens entirely in your browser. Your document is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the output PDF." },
  ],
  "watermark-pdf": [
    { q: "Can I add a diagonal watermark to a PDF?", a: "Yes. Select a diagonal angle for the watermark text so it appears across the center of each page at 45°, which is the most common watermark orientation for 'CONFIDENTIAL' or 'DRAFT' stamps." },
    { q: "Will the watermark be removable?", a: "For PDFs without edit restrictions, a skilled user can remove a text watermark using Adobe Acrobat. For a more permanent watermark, flatten the PDF after watermarking." },
    { q: "Can I watermark every page?", a: "Yes. The watermark is applied to every page of the PDF automatically." },
    { q: "Is this free?", a: "Yes, completely free. Watermark is applied in your browser with no file upload to any server." },
  ],
  "sign-pdf": [
    { q: "Is a digital signature legally valid?", a: "Electronic signatures are legally valid in most countries under laws like eSign Act (US), eIDAS (EU), and IT Act (India). However, for high-stakes legal documents, a certificate-based digital signature (DSC) may be required." },
    { q: "Can I draw my signature?", a: "Yes. Draw your signature with a mouse or finger (on touchscreen), or type your name and choose from signature font styles." },
    { q: "Is my signed PDF private?", a: "Yes. Signing happens entirely in your browser. Your PDF and signature are never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark and no account required." },
  ],
  "lock-pdf": [
    { q: "What does locking a PDF do?", a: "Locking adds a password that must be entered before the PDF can be opened. Without the password, the file cannot be viewed, edited, printed, or copied." },
    { q: "What encryption does this tool use?", a: "The tool uses AES-256 encryption (the same standard used by banks and governments) for PDF password protection. This is virtually impossible to brute-force with a strong password." },
    { q: "Will the password work in all PDF readers?", a: "Yes. The password protection follows the PDF standard and works in Adobe Acrobat Reader, Chrome's PDF viewer, Preview (macOS), Foxit, and all other major PDF readers." },
    { q: "Is this free?", a: "Yes, completely free. Your PDF is encrypted locally in your browser." },
  ],
  "unlock-pdf": [
    { q: "When can I unlock a PDF?", a: "You can only remove password protection if you know the current password. This tool is designed for legitimate use — removing the password from your own PDFs for convenience." },
    { q: "Does unlocking remove all restrictions?", a: "The tool removes the open password (required to view) and owner password (restricts editing/printing). The unlocked PDF can then be freely opened, edited, and printed." },
    { q: "Is my PDF private?", a: "Yes. Password removal happens entirely in your browser. Your document and password are never sent to any server." },
    { q: "Is this free?", a: "Yes, completely free. No file size limit is imposed by PreppTools." },
  ],
  "pdf-to-image": [
    { q: "What image format does it output?", a: "Pages are exported as PNG images for lossless quality, suitable for archiving. JPEG output is also available for smaller file sizes when exact reproduction is less critical." },
    { q: "Can I export only specific pages?", a: "Yes. Specify page numbers or ranges to export only the pages you need rather than the entire document." },
    { q: "What resolution is the output?", a: "The tool renders at 150–300 DPI depending on the setting. 150 DPI is sufficient for screen viewing; 300 DPI is the standard for print quality." },
    { q: "Is this free?", a: "Yes, completely free. Your PDF is converted locally in your browser." },
  ],
  "pdf-to-text": [
    { q: "Does it work on scanned PDFs?", a: "No. Scanned PDFs are images of text, not actual text. This tool extracts embedded text from digitally-created PDFs. For scanned documents, you need OCR (Optical Character Recognition) software." },
    { q: "Will the extracted text preserve formatting?", a: "Paragraph breaks are preserved but complex layouts (columns, tables, sidebars) may not extract in reading order. The output is plain text — headings and styling are not preserved." },
    { q: "What encoding is used for the output?", a: "The text is output as UTF-8, which supports all languages including those with non-Latin characters (Arabic, Chinese, Hindi, etc.)." },
    { q: "Is this free?", a: "Yes, completely free. Text is extracted locally in your browser." },
  ],
  "pdf-to-word": [
    { q: "Will the converted Word document look exactly like the PDF?", a: "Not always. Complex layouts with columns, callout boxes, and precise formatting may shift. The tool prioritizes accurate text extraction over exact layout reproduction." },
    { q: "What format is the output?", a: "The output is an RTF (Rich Text Format) file, which can be opened directly in Microsoft Word, Google Docs, LibreOffice Writer, and most word processors." },
    { q: "Does it work on scanned PDFs?", a: "No. Scanned PDFs contain image data, not extractable text. This tool works only with digitally-created PDFs that have embedded text." },
    { q: "Is this free?", a: "Yes, completely free with no file size limit imposed by PreppTools." },
  ],
  "ppt-to-pdf": [
    { q: "Will animations and transitions be preserved?", a: "No. PDF is a static format — animations, transitions, and embedded videos from PowerPoint do not transfer. Each slide becomes a static page in the PDF." },
    { q: "Will fonts look the same in the PDF?", a: "If the fonts are embedded in the .pptx file, they will render correctly. If the font isn't embedded and isn't installed on your device, a fallback font may be substituted." },
    { q: "Is my presentation private?", a: "Yes. Conversion happens entirely in your browser. Your PowerPoint file is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no file size limit imposed by PreppTools." },
  ],
  "excel-to-csv": [
    { q: "Which sheet gets exported?", a: "The first (active) sheet is exported by default. If your Excel workbook has multiple sheets, rename the one you want exported to make it the first sheet before uploading." },
    { q: "What delimiter does the CSV use?", a: "Commas by default (standard CSV). Some tools use the TSV (tab-separated) variant for data with commas in values. Check your target application's import requirements." },
    { q: "Will formulas be exported?", a: "Calculated values are exported, not the formulas. The CSV will contain the result of each formula as a plain number or text value." },
    { q: "Is this free?", a: "Yes, completely free. Your Excel file is processed locally in your browser." },
  ],
  "csv-to-excel": [
    { q: "Does it support semicolon-separated files?", a: "Yes. European CSV files often use semicolons (;) instead of commas as the delimiter. The tool auto-detects the delimiter or lets you specify it manually." },
    { q: "What happens to quoted fields with commas inside?", a: "Quoted fields (e.g. 'Smith, John') are correctly parsed — the comma inside quotes is treated as content, not a separator. RFC 4180-compliant CSV parsing is applied." },
    { q: "Will the Excel file have proper column types?", a: "Numbers, dates, and text are auto-detected and formatted in the appropriate Excel column type. This prevents numbers from being stored as text (a common import issue)." },
    { q: "Is this free?", a: "Yes, completely free. Your CSV file is converted locally in your browser." },
  ],
  "excel-to-pdf": [
    { q: "Will all columns fit on the PDF page?", a: "Wide spreadsheets may need to be set to landscape orientation or scaled down to fit. Adjust your print area and page setup in Excel before uploading for the best PDF layout." },
    { q: "Can I export multiple sheets?", a: "Currently, the first active sheet is exported. For multi-sheet exports, consider using Microsoft Excel's built-in 'Export to PDF' feature, which handles complex multi-sheet layouts." },
    { q: "Is my spreadsheet private?", a: "Yes. Conversion happens entirely in your browser. Your Excel file is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the output PDF." },
  ],
  "crop-pdf": [
    { q: "Does cropping permanently remove content?", a: "No. PDF cropping sets the visible 'crop box' area but the hidden content is still technically in the file and can be restored. To permanently remove content, use the redaction feature in Adobe Acrobat." },
    { q: "Can I crop to remove white margins from scanned documents?", a: "Yes. This is one of the most common uses — scanned PDFs often have large white margins. Set tight crop margins to focus the page on just the content area." },
    { q: "Is my PDF private?", a: "Yes. Cropping happens entirely in your browser. Your document is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the output." },
  ],
  "edit-pdf": [
    { q: "Can I edit existing text in a PDF?", a: "This tool lets you add new text boxes and annotations on top of a PDF. Editing the original embedded text in a PDF requires the source document (Word, InDesign, etc.) or a full PDF editor like Adobe Acrobat." },
    { q: "What annotations can I add?", a: "Text boxes, sticky notes, and freehand drawing/highlights. These are standard PDF annotation types visible in all PDF readers." },
    { q: "Is my PDF private?", a: "Yes. Editing happens entirely in your browser. Your document is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the annotated PDF." },
  ],
  "flatten-pdf": [
    { q: "What does flattening do exactly?", a: "Flattening merges interactive form fields, annotations, and signature layers into the base page content, converting them to static graphics. The PDF becomes read-only — form fields can no longer be edited." },
    { q: "When should I flatten a PDF?", a: "Before submitting completed forms to government agencies, banks, or clients who shouldn't be able to modify the data. Also useful before archiving documents to ensure they look the same in all future PDF readers." },
    { q: "Is my PDF private?", a: "Yes. Flattening happens entirely in your browser. Your document is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the flattened PDF." },
  ],
  "grayscale-pdf": [
    { q: "How much does converting to grayscale reduce file size?", a: "Color information is removed, which typically reduces PDF file size by 20–50% depending on how many color images are in the document." },
    { q: "Will text remain sharp in grayscale?", a: "Yes. Text rendered from embedded fonts converts perfectly to grayscale with no quality loss. Raster images (photos) may show some quality reduction." },
    { q: "Is my PDF private?", a: "Yes. Grayscale conversion happens entirely in your browser. Your document is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark and no file size limit." },
  ],
  "header-footer-pdf": [
    { q: "Can I include page numbers in the header or footer?", a: "Yes. Use the {page} and {total} placeholders to automatically insert page numbers (e.g. 'Page 3 of 12') in any position — left, center, or right." },
    { q: "Can I add the current date?", a: "Yes. Use the {date} placeholder and the current date will be inserted automatically when generating the PDF." },
    { q: "Is my PDF private?", a: "Yes. All processing happens in your browser. Your document is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the output PDF." },
  ],
  "page-numbers-pdf": [
    { q: "Where can page numbers be placed?", a: "Bottom center, bottom left, bottom right, top center, top left, or top right — all standard positions are supported." },
    { q: "Can I start numbering from a specific number?", a: "Yes. If your document already has a cover page or front matter, you can start the page counter from any number (e.g. start at 3 to match the document's internal numbering)." },
    { q: "Is my PDF private?", a: "Yes. Page numbering happens entirely in your browser. Your document is never uploaded to any server." },
    { q: "Is this free?", a: "Yes, completely free with no watermark on the numbered PDF." },
  ],
  "countdown-timer": [
    { q: "Will the timer alert me when it finishes?", a: "Yes. An audio alert plays when the countdown reaches zero. Make sure your device volume is on and browser audio is not blocked." },
    { q: "Can I use this as a study or exam timer?", a: "Yes. Set your exam duration (e.g. 1 hour 30 minutes) and the timer counts down exactly. Used by students for timed practice tests and exam simulations." },
    { q: "Does the timer work if I switch tabs?", a: "Yes. The timer runs in JavaScript and continues counting even when the tab is in the background. The alarm fires correctly when time is up." },
    { q: "Is this free?", a: "Yes, completely free and works in any modern browser without installation." },
  ],
  "pomodoro-timer": [
    { q: "What is the Pomodoro technique?", a: "Developed by Francesco Cirillo in the late 1980s, the Pomodoro technique breaks work into 25-minute focused sessions (called pomodoros) separated by 5-minute breaks. After 4 pomodoros, take a 15–30 minute long break." },
    { q: "Can I customize the session length?", a: "Yes. Adjust the work session, short break, and long break durations to match your personal rhythm. Some people prefer 50-minute sessions with 10-minute breaks." },
    { q: "Does the timer track how many pomodoros I've completed?", a: "Yes. Each completed session increments the pomodoro counter. After 4 sessions, the tool prompts you to take a long break." },
    { q: "Is this free?", a: "Yes, completely free and works in any modern browser without installation." },
  ],
  "freelancer-hub": [
    { q: "How is the recommended hourly rate calculated?", a: "The calculator takes your target annual income, divides it by your available billable hours (after deducting weeks off and non-billable time), then adds your business expenses and desired profit margin. The result is the minimum hourly rate you need to charge to meet your income goal." },
    { q: "Which freelance platforms does the fee calculator cover?", a: "The platform fee calculator covers Upwork, Fiverr, Toptal, Freelancer.com, and PeoplePerHour — showing the commission deducted and your actual take-home for any project value you enter." },
    { q: "Does Upwork's fee change based on earnings with a client?", a: "Yes. Upwork uses a sliding scale: 20% on the first $500 with a client, 10% from $500–$10,000, and 5% above $10,000. The calculator reflects these tiers based on the project value you enter." },
    { q: "Should my hourly rate include taxes?", a: "Yes. As a freelancer you pay both sides of taxes, so set aside 25–35% of income for tax and factor that into your income target before using the calculator." },
    { q: "Is this tool free?", a: "Yes, completely free with no sign-up required. Both calculators run entirely in your browser." },
  ],
  "ai-logo-maker": [
    { q: "What file formats can I download my logo in?", a: "You can download your logo as SVG (infinitely scalable, ideal for websites and print) or PNG at 3× resolution (perfect for social media, presentations, and app icons)." },
    { q: "Do I need design skills to use this?", a: "No. Just enter your brand name, pick a style preset or customise colours and shapes, and your logo is generated instantly. No Photoshop or Canva account needed." },
    { q: "Can I use the logo commercially?", a: "Yes. Logos generated with this free tool are yours to use for any personal or commercial purpose — websites, business cards, merchandise, and more." },
    { q: "What makes an SVG logo better than a PNG?", a: "SVG is a vector format, meaning it scales to any size without ever pixelating. A single SVG works perfectly on a tiny favicon and a large billboard. PNG is a fixed-resolution image — great for sharing but not for scaling." },
    { q: "Is this logo maker free?", a: "Yes, completely free with no account required. Everything runs in your browser." },
  ],
  "ai-ad-copy-generator": [
    { q: "Which advertising platforms does this support?", a: "The generator creates tailored copy for Google Ads, Facebook, Instagram, and LinkedIn — each with platform-specific headlines, body copy, and call-to-action formats." },
    { q: "What tones are available?", a: "Five tones: Professional, Casual, Urgent, Inspiring, and Humorous. Each produces noticeably different copy suited to different brand voices and campaign goals." },
    { q: "Can I use the generated copy directly in my ad manager?", a: "Yes. The output is structured as a headline, body, and CTA — exactly the format ad platforms expect. Just copy and paste." },
    { q: "How many variations can I generate?", a: "Unlimited. Change the tone, platform, or any input and click Generate again to get a fresh version instantly." },
    { q: "Is this free?", a: "Yes, completely free with no account or subscription required." },
  ],
  "ai-hashtag-generator": [
    { q: "Which platforms are supported?", a: "Instagram, Twitter/X, LinkedIn, TikTok, and YouTube. Each platform generates hashtags suited to that platform's culture and algorithm." },
    { q: "How many hashtags should I use per post?", a: "Instagram: 5–15 (quality over quantity since the 2022 algorithm update). Twitter/X: 1–2. LinkedIn: 3–5. TikTok: 3–5 focused tags. YouTube: up to 15 in the description." },
    { q: "Will using too many hashtags get my post shadowbanned?", a: "Using irrelevant or spammy hashtags can reduce reach. This generator produces topic-relevant hashtags to minimise that risk. Stick to 10–15 on Instagram and avoid banned or overused tags." },
    { q: "Can I generate hashtags for any niche?", a: "Yes. Enter any topic — fitness, food, travel, SaaS, real estate, fashion — and the generator produces relevant hashtags for that niche." },
    { q: "Is this free?", a: "Yes, completely free with no sign-up required." },
  ],
  "ai-bio-generator": [
    { q: "Which platforms does the bio generator support?", a: "Instagram, Twitter/X, LinkedIn, GitHub, and YouTube. Each platform has different character limits and audience expectations, and the generator tailors the bio accordingly." },
    { q: "What is the character limit for each platform bio?", a: "Instagram: 150 characters. Twitter/X: 160 characters. LinkedIn: 220 characters (summary). GitHub: 160 characters. YouTube: up to 1,000 characters (channel description)." },
    { q: "Can I generate multiple versions to pick the best one?", a: "Yes. Change the tone (Professional, Witty, Inspiring, Casual, or Bold) and click Generate again to get a different version instantly. Mix and match lines from different versions." },
    { q: "Should I edit the generated bio?", a: "Yes — always personalise it. Add a specific achievement, a link, your location, or an emoji that fits your brand. The generator gives you a strong starting point; your personal touch makes it authentic." },
    { q: "Is this free?", a: "Yes, completely free with no account required." },
  ],
  "ai-email-subject-generator": [
    { q: "How many subject lines does it generate?", a: "Three subject line options per generation, each with a distinct angle. You can copy any one individually or regenerate instantly for more options." },
    { q: "What email purposes are supported?", a: "Newsletter, Cold Outreach, Sales/Promo, Re-engagement, Product Launch, and Event Invite — covering the most common email marketing use cases." },
    { q: "What is a good email open rate?", a: "The average email open rate across industries is 20–25%. A strong subject line can push this to 35–50%. Personalisation, urgency, and curiosity-based subject lines consistently outperform generic ones." },
    { q: "Should I A/B test subject lines?", a: "Absolutely. Even a small improvement in open rate compounds over time. Generate 2–3 variations with this tool and split-test them in your email platform to find what resonates with your audience." },
    { q: "Is this free?", a: "Yes, completely free with no account or subscription required." },
  ],
};
