export type Question = {
  q: string;
  category: string;
  tip: string;
  sample: string;
};

export type Role = {
  id: string;
  label: string;
  icon: string;
  color: string;
  bg: string;
  questions: Question[];
};

export const roles: Role[] = [
  {
    id: "software-engineer",
    label: "Software Engineer",
    icon: "💻",
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-700",
    questions: [
      { q: "Tell me about yourself.", category: "General", tip: "Keep it under 2 minutes. Cover: current role → key experience → why you're here.", sample: "I'm a backend engineer with 3 years of experience building scalable APIs in Node.js. At my current company I led the migration from a monolith to microservices, reducing response time by 40%. I'm looking for a role where I can work on more complex distributed systems problems." },
      { q: "Describe a challenging bug you fixed.", category: "Technical", tip: "Use STAR format. Focus on your debugging process, not just the fix.", sample: "We had a memory leak in production that only appeared under load. I used heap snapshots in Chrome DevTools to trace it to an unclosed event listener in our WebSocket handler. Fixed it, added a unit test, and documented the pattern for the team." },
      { q: "How do you handle tight deadlines?", category: "Behavioural", tip: "Show you prioritise ruthlessly and communicate proactively — not that you just 'work harder'.", sample: "I break the scope into must-have vs nice-to-have, communicate the trade-offs to the PM early, and focus on shipping a working core first. I also flag blockers on day 1, not day 5." },
      { q: "Walk me through a project you're most proud of.", category: "Technical", tip: "Pick one with clear impact. Numbers help — latency reduced, users served, uptime improved.", sample: "I built a real-time notification service handling 2M events/day using Kafka and Redis. It replaced a polling system that was causing 30% of our DB load. Took 6 weeks, zero downtime migration." },
      { q: "How do you approach code reviews?", category: "Collaboration", tip: "Mention both giving and receiving feedback. Show you treat it as a learning tool, not gatekeeping.", sample: "I review for correctness first, then readability. I leave suggestions, not demands — 'consider X because Y' rather than 'do X'. When receiving reviews, I assume good intent and ask questions before defending my approach." },
      { q: "Tell me about a time you disagreed with a teammate.", category: "Behavioural", tip: "Show you can disagree professionally and commit to a decision once made.", sample: "My colleague wanted to use a NoSQL database for a feature I felt needed ACID guarantees. I prepared a short doc comparing both approaches for the use case, presented it to the team, and we agreed on Postgres. The feature had zero data consistency issues in production." },
      { q: "How do you stay current with new technologies?", category: "Growth", tip: "Be specific — name actual sources, communities, or projects. Vague answers like 'I read blogs' don't land.", sample: "I follow engineering blogs from companies like Cloudflare, Stripe, and Netflix. I spend one weekend a month building a small project with something new — recently I built a CLI tool using Rust. I also attend local meetups quarterly." },
      { q: "How do you ensure code quality?", category: "Technical", tip: "Cover: testing strategy, linting, reviews, documentation. Show it's a system, not an afterthought.", sample: "I write unit tests for business logic, integration tests for APIs, and E2E for critical user flows. I enforce linting via CI so no PR merges with errors. I also document non-obvious decisions in code comments — not what, but why." },
      { q: "Describe a time you had to learn something quickly.", category: "Growth", tip: "Show your learning process, not just that you did it. Interviewers want to see how you learn.", sample: "We needed Kubernetes in 3 weeks for a client requirement. I did the official tutorial, then deployed a staging clone, breaking and fixing things deliberately. By week 2 I was writing Helm charts. By week 3 I had trained two teammates." },
      { q: "Where do you see yourself in 3 years?", category: "General", tip: "Be honest but align with the company's growth path. Show ambition without arrogance.", sample: "I want to grow into a senior/staff engineer role where I'm influencing technical decisions across teams, not just within a squad. I'm especially interested in deepening my distributed systems expertise." },
    ],
  },
  {
    id: "product-manager",
    label: "Product Manager",
    icon: "🗺️",
    color: "text-purple-600 dark:text-purple-400",
    bg: "bg-purple-50 dark:bg-purple-900/20 border-purple-200 dark:border-purple-700",
    questions: [
      { q: "Tell me about yourself.", category: "General", tip: "Frame it as: product you've owned → impact you drove → why this role/company.", sample: "I'm a PM with 4 years of experience in B2C fintech. At my last company I owned the onboarding flow, which I redesigned to increase Day-7 retention by 22%. I'm looking for a role where I can work on more complex, data-informed product decisions at scale." },
      { q: "How do you prioritise features?", category: "Strategy", tip: "Name a framework (RICE, ICE, MoSCoW) but show you adapt to context. Frameworks are tools, not rules.", sample: "I typically use RICE — Reach, Impact, Confidence, Effort. But I overlay it with strategic alignment: a low-RICE feature might still be P0 if it's blocking an enterprise deal. I also run weekly prioritisation syncs with engineering and design to keep everyone aligned." },
      { q: "Tell me about a product failure.", category: "Behavioural", tip: "Interviewers want to see self-awareness and what you learned. Don't deflect blame.", sample: "We launched a referral feature that flopped — 0.3% adoption vs 8% projected. In hindsight, I hadn't validated the incentive model with enough users. We ran 5 user interviews and found people wanted discounts, not credits. We relaunched with discounts and hit 6% adoption." },
      { q: "How do you gather user feedback?", category: "Research", tip: "Show a mix of qualitative and quantitative methods. Don't just say 'user interviews'.", sample: "I use a stack: Mixpanel for funnel analysis, NPS surveys at key moments, monthly user interviews (I do 4–6 myself, not just via UXR), and a Slack channel where power users can submit feedback directly. I synthesise all of this into a monthly insight doc." },
      { q: "How do you define success for a product?", category: "Strategy", tip: "Tie success to business outcomes, not just usage metrics. Show you think beyond vanity metrics.", sample: "I define success at three levels: leading indicators (engagement, feature adoption), lagging indicators (retention, revenue), and qualitative signals (NPS, support ticket themes). A feature is only successful when it moves a lagging indicator, not just a usage number." },
      { q: "How do you work with engineering teams?", category: "Collaboration", tip: "Show respect for engineering constraints and that you involve them early, not just at handoff.", sample: "I bring engineers into discovery, not just delivery. Before writing a PRD, I do a 30-minute 'problem briefing' with the tech lead to understand constraints. This catches blockers early and leads to better solutions — engineers often surface ideas I hadn't considered." },
      { q: "How do you handle stakeholder disagreements?", category: "Behavioural", tip: "Show you use data and user insight to facilitate decisions, not authority or politics.", sample: "I had a sales leader pushing for a feature I felt wasn't ready. Instead of debating opinions, I proposed a 2-week spike: we'd build a prototype and test it with 5 target customers. The data showed mixed results, and we agreed on a scoped version that shipped 6 weeks later with better outcomes." },
      { q: "How do you build a product roadmap?", category: "Strategy", tip: "Show it's outcome-based, not feature-based. Roadmaps should answer 'why', not just 'what'.", sample: "My roadmaps are outcome-based — each theme maps to a business or user goal, not a list of features. I do quarterly planning with annual themes, and keep a rolling 6-week execution plan. I share a public-facing version with stakeholders and an internal version with more detail for the team." },
      { q: "How do you make decisions with limited data?", category: "Strategy", tip: "Show a process for making calibrated bets — not paralysis, not gut feeling alone.", sample: "I identify what type of decision it is: reversible or irreversible. For reversible ones I move fast with a lightweight hypothesis. For irreversible ones I slow down and gather the minimum viable data needed. I also make my assumptions explicit so the team can flag if they disagree." },
      { q: "What metrics do you track for product health?", category: "Analytics", tip: "Show a north star metric plus a small set of supporting metrics. Avoid listing 20 metrics.", sample: "My north star is usually a retention metric — DAU/MAU or Week-4 retention depending on the product. Supporting metrics: activation rate, feature adoption, NPS, and support ticket volume. I track these weekly and set up anomaly alerts for anything that moves more than 15% week-over-week." },
    ],
  },
  {
    id: "marketing",
    label: "Marketing",
    icon: "📣",
    color: "text-pink-600 dark:text-pink-400",
    bg: "bg-pink-50 dark:bg-pink-900/20 border-pink-200 dark:border-pink-700",
    questions: [
      { q: "Tell me about yourself.", category: "General", tip: "Lead with a specific campaign win, then your background, then your goal.", sample: "I'm a digital marketer with 5 years of experience in B2B SaaS. My biggest win was a content campaign that generated 3,000 organic leads in 90 days, reducing our CPL by 60%. I'm looking for a role where I can build full-funnel marketing strategy, not just run campaigns." },
      { q: "Walk me through a successful campaign you ran.", category: "Experience", tip: "Use STAR. Quantify results — clicks, leads, CAC, ROAS. Don't be vague.", sample: "We needed to enter a new segment — mid-market finance. I built a 3-month ABM campaign: LinkedIn ads targeting CFOs, personalised landing pages per industry, and a 7-email nurture sequence. Result: 40 MQLs, 12 demos, 4 closed deals worth ₹28L in ARR." },
      { q: "How do you measure ROI on a campaign?", category: "Analytics", tip: "Show you track the full funnel from spend to revenue, not just clicks or impressions.", sample: "I track spend → clicks → MQLs → SQLs → closed deals. For each campaign I calculate CPL, MQL-to-SQL rate, and pipeline-to-spend ratio. For brand campaigns I use incrementality testing — running the campaign in some regions and not others to measure lift." },
      { q: "How do you approach an SEO strategy?", category: "Technical", tip: "Show you understand both technical SEO and content strategy. Name tools you use.", sample: "I start with a keyword gap analysis using Semrush, then audit technical issues — crawlability, Core Web Vitals, structured data. Then I build a content calendar targeting bottom-of-funnel keywords first (highest purchase intent), then expand to informational content for top-of-funnel." },
      { q: "Describe a campaign that failed.", category: "Behavioural", tip: "Own it. Show what you learned and changed. Interviewers value self-awareness.", sample: "I ran a webinar series that had 400 registrations but only 40 attendees — 10% show rate. I hadn't segmented the audience well and the topic was too broad. I restructured to niche webinars for specific personas, and our next series had a 38% show rate." },
      { q: "How do you create content for different audiences?", category: "Strategy", tip: "Show you start with persona research, not just write and hope.", sample: "I start by mapping the audience's key pain point, their level of awareness, and their preferred content format. A CTO needs a technical deep-dive; a CEO wants an executive summary. I create one core piece and repurpose it — long-form blog → LinkedIn carousel → short video → email." },
      { q: "What's your experience with paid ads?", category: "Technical", tip: "Be specific about platforms, budget managed, and results. Avoid generic answers.", sample: "I've managed Google Ads and LinkedIn Ads with combined monthly budgets up to ₹8L. My best Google Ads campaign achieved a ROAS of 4.2x. I A/B test ad copy constantly — usually running 3 variants per ad group — and I kill underperformers within 7 days." },
      { q: "How do you stay updated on marketing trends?", category: "Growth", tip: "Name specific newsletters, communities, or people you follow. Generic answers fail.", sample: "I read Marketing Brew daily, follow the SparkToro blog for audience research insights, and am active in the Exit Five community for B2B marketing. I also run small experiments on my own projects to test trends before pitching them at work." },
      { q: "How do you align marketing with sales?", category: "Collaboration", tip: "Show you understand the MQL→SQL handoff and have fixed friction between teams before.", sample: "The biggest issue I've seen is MQL definition misalignment. I run a quarterly session with sales to review which leads converted and why. We co-define the ICP together and I set up a shared Slack channel so AEs can flag bad leads in real time, which feeds back into my targeting." },
      { q: "How do you handle a small budget?", category: "Strategy", tip: "Show creativity and prioritisation. Interviewers want resourceful marketers, not ones who just need more money.", sample: "I focus on owned and earned channels first — SEO, content, partnerships. For paid, I pick one channel and go deep rather than spreading thin. I've got strong results with micro-influencer partnerships where ₹50k spent outperformed ₹3L on Google Ads in the same quarter." },
    ],
  },
  {
    id: "hr",
    label: "HR / People",
    icon: "🤝",
    color: "text-green-600 dark:text-green-400",
    bg: "bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-700",
    questions: [
      { q: "Tell me about yourself.", category: "General", tip: "Cover: your HR specialisation → a key initiative → what drives you.", sample: "I'm an HR generalist with 6 years of experience, with a focus on talent acquisition and people operations. At my last company I built the onboarding programme from scratch, which improved 30-day retention by 18%. I'm passionate about creating workplaces where people do their best work." },
      { q: "How do you handle conflict between employees?", category: "Behavioural", tip: "Show a clear, fair process. Mention confidentiality, active listening, and following up.", sample: "I meet each person separately first to hear their perspective without the other present. Then I bring them together to find common ground. I document the conversation and agreed actions, and follow up in 2 weeks to ensure the issue hasn't resurfaced. I also look for systemic causes — was this a process problem, not a people problem?" },
      { q: "Describe your approach to hiring.", category: "Recruitment", tip: "Show you think about bias, candidate experience, and hiring for culture add — not just fit.", sample: "I start by writing a clear job scorecard, not just a job description — defining what success looks like in 30/60/90 days. I use structured interviews with consistent questions across candidates to reduce bias. I also ensure a diverse interview panel and give candidates a realistic job preview to reduce early attrition." },
      { q: "How do you handle a performance issue?", category: "Behavioural", tip: "Show a fair, documented process. Mention the PIPs, support offered, and legal compliance.", sample: "I follow a clear process: informal conversation first, then a formal PIP with specific, measurable expectations and timelines. I check in weekly and document everything. I also ensure the manager is providing support, not just monitoring. If things don't improve, I follow the documented process to offboard with dignity." },
      { q: "How do you measure employee engagement?", category: "Analytics", tip: "Show a multi-method approach — not just the annual survey.", sample: "I run quarterly pulse surveys (5 questions max — people actually complete them), monthly 1:1 skip-level meetings, and track leading indicators like voluntary attrition and internal mobility rate. I share results transparently with leadership and co-create action plans with team leads, not just present a report." },
      { q: "How do you handle a confidential situation?", category: "Ethics", tip: "Show you understand the balance between confidentiality and duty to act.", sample: "I treat all HR conversations as confidential unless there's a legal obligation or safety risk. If someone shares something that crosses that threshold, I explain upfront that I'll need to escalate and why. I never share more than necessary — only what's needed to resolve the issue." },
      { q: "Describe an HR policy you implemented.", category: "Experience", tip: "Show the business case, rollout process, and measured outcome.", sample: "I introduced a flexible work policy allowing employees to choose their core hours within a 7am–7pm window. I piloted it with one team for 8 weeks, gathered data on productivity and satisfaction, then rolled it out company-wide. Employee satisfaction scores increased by 14 points in the next survey." },
      { q: "How do you stay updated on labour laws?", category: "Compliance", tip: "Name specific sources. Show you act proactively, not reactively.", sample: "I subscribe to updates from the Ministry of Labour website and the SHRM India newsletter. I also have a relationship with our employment lawyer who sends quarterly briefings. When a law changes, I update our policies within 30 days and brief managers in the next team lead sync." },
      { q: "How do you build culture in a remote team?", category: "Strategy", tip: "Show specific initiatives, not just 'we have virtual team lunches'.", sample: "I focus on async-first documentation so everyone has context regardless of timezone, plus structured connection rituals — monthly virtual coffees randomly paired, a #wins channel, and quarterly in-person offsites for relationship-building. Culture is built in small consistent moments, not big events." },
      { q: "What's your approach to compensation and benchmarking?", category: "Compensation", tip: "Show you use data and maintain internal equity alongside market competitiveness.", sample: "I benchmark annually using Radford or Mercer data, plus local surveys for India-specific roles. I build salary bands with clear ranges and progression criteria so managers can have transparent conversations. I also run an internal equity audit every 18 months to catch pay gaps before they become problems." },
    ],
  },
  {
    id: "finance",
    label: "Finance / Accounts",
    icon: "📊",
    color: "text-amber-600 dark:text-amber-400",
    bg: "bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-700",
    questions: [
      { q: "Tell me about yourself.", category: "General", tip: "Lead with a financial achievement, not your education. Show business impact.", sample: "I'm a finance professional with 5 years in FP&A. I recently built a three-statement financial model that identified ₹1.2Cr in cost savings across supply chain. I'm looking for a role where I can work closer to strategic decision-making, not just reporting." },
      { q: "Walk me through a financial model you built.", category: "Technical", tip: "Be specific about the model type, inputs, outputs, and how it was used in decisions.", sample: "I built a DCF model for a potential acquisition. Inputs were 5-year revenue projections, margin assumptions, and WACC from our cost of capital analysis. Output was a valuation range with sensitivity tables on growth rate and terminal multiple. The model was presented to the board and informed the decision not to proceed at the asking price." },
      { q: "How do you handle discrepancies in financial reports?", category: "Technical", tip: "Show a systematic reconciliation process — not panic.", sample: "I start by identifying which line item has the discrepancy and trace it back to the source data. Usually it's a cut-off issue or a double-posting. I document the finding, correct the entry, and implement a control to prevent recurrence — usually a reconciliation checklist for that account type." },
      { q: "How do you explain financial data to non-finance stakeholders?", category: "Communication", tip: "Show you translate numbers into business language. Avoid jargon.", sample: "I lead with the 'so what', not the number. Instead of 'EBITDA decreased 8%', I say 'we retained ₹40L less cash this quarter, primarily because marketing spend doubled without a proportional revenue increase — here's what I recommend we do.' I use visuals and keep slides to one insight per page." },
      { q: "Describe your experience with financial forecasting.", category: "Technical", tip: "Mention your forecasting method, accuracy tracking, and how you handle uncertainty.", sample: "I build rolling 12-month forecasts refreshed monthly. I use driver-based models — revenue driven by units × price, not just last year + X%. I track forecast accuracy vs actuals and investigate any variance over 5%. My last annual forecast was within 3.2% of actual revenue." },
      { q: "Describe a cost-saving initiative you led.", category: "Experience", tip: "Quantify the saving. Show you got buy-in and implemented it sustainably.", sample: "I audited our SaaS subscriptions and found 14 tools with overlapping functionality. I presented a consolidation plan to leadership with a cost-benefit analysis — ₹18L annual saving for ₹2L migration cost. Implemented over 3 months with zero operational disruption." },
      { q: "How do you manage month-end close?", category: "Operations", tip: "Show a structured, timeline-driven process with clear ownership.", sample: "I run close on a day-by-day checklist: Day 1-3 for sub-ledger reconciliations, Day 4-5 for accruals and journal entries, Day 6-7 for management reporting. I have a shared tracker every team updates in real time. My last close process averaged 7 business days, down from 12 when I joined." },
      { q: "What financial tools and software do you use?", category: "Technical", tip: "Name specific tools and what you use them for — not just a list.", sample: "I use Tally for accounting, Excel with Power Query for modelling and data transformation, and Power BI for management dashboards. I've also worked with SAP for large-entity consolidations and Zoho Books for SME clients. I'm comfortable building complex models from scratch in Excel." },
      { q: "How do you stay updated on regulatory changes?", category: "Compliance", tip: "Show proactive tracking — specific sources, not 'I read the news'.", sample: "I follow ICAI announcements, MCA filings updates, and GST council circulars via their official newsletters. I set Google Alerts for key topics. When a change impacts our business, I prepare a one-page impact brief for leadership within 48 hours and update our compliance calendar." },
      { q: "How do you handle pressure during audit season?", category: "Behavioural", tip: "Show preparation, prioritisation, and team leadership under pressure.", sample: "Preparation is the only answer. I maintain a permanent audit file that I update monthly — no scrambling for documents. During audit season I create a request tracker shared with the audit team so nothing falls through. I also brief my team two weeks in advance and reallocate work to protect key people from burnout." },
    ],
  },
  {
    id: "sales",
    label: "Sales",
    icon: "🎯",
    color: "text-red-600 dark:text-red-400",
    bg: "bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-700",
    questions: [
      { q: "Tell me about yourself.", category: "General", tip: "Lead with a quota number and your win rate. Sales interviewers want proof of performance first.", sample: "I'm a B2B SaaS AE with 4 years of experience, consistently hitting 115%+ of quota. Last year I closed ₹2.4Cr in new ARR, including our largest enterprise deal at ₹38L. I specialise in complex, multi-stakeholder deals with 60–90 day cycles." },
      { q: "Walk me through your sales process.", category: "Process", tip: "Show a structured, repeatable process — not 'I build relationships and close deals'.", sample: "Prospect → Qualify (BANT or MEDDIC) → Discovery call to uncover pain → Demo tailored to their use case → Proposal with ROI model → Negotiation → Close. I document every step in the CRM and use mutual action plans with champions to keep deals moving." },
      { q: "How do you handle rejection?", category: "Behavioural", tip: "Show emotional resilience and a learning mindset — not that it doesn't affect you.", sample: "I don't take it personally, but I do take it seriously. After every lost deal I run a post-mortem: was it budget, timing, competition, or my execution? If it's my execution, I fix it. I also ask prospects directly why they went with a competitor — most will tell you if you ask the right way." },
      { q: "Describe your biggest sales win.", category: "Experience", tip: "Use STAR. Include the deal size, the obstacle you overcame, and what you did differently.", sample: "My biggest win was a ₹52L enterprise deal. The champion left mid-cycle and their replacement was skeptical. I rebuilt the relationship from scratch, got an executive sponsor involved, and created a business case the new champion could present internally. Closed in 11 weeks after the setback." },
      { q: "How do you research a prospect before a call?", category: "Process", tip: "Show a systematic pre-call ritual — not just 'I check LinkedIn'.", sample: "I spend 20 minutes pre-call: LinkedIn for their background and recent activity, company news for growth signals or pain points, their job postings to understand priorities, and their G2/Trustpilot reviews to understand competitor weaknesses. I write 3 hypothesis questions based on what I find." },
      { q: "How do you handle common objections?", category: "Skills", tip: "Pick 2–3 specific objections and show your actual response — not generic frameworks.", sample: "For 'too expensive': I refocus on ROI — 'Let's look at what not solving this costs you'. For 'we're happy with the current solution': 'What would have to change for you to re-evaluate?' For 'not the right time': 'What would make the timing right?' I never argue — I get curious." },
      { q: "How do you hit targets in a slow market?", category: "Strategy", tip: "Show creativity and pipeline discipline — not just 'I work harder'.", sample: "In a slow market I focus on existing customers first — expansion and upsell have shorter cycles and higher win rates. I also go deeper into my pipeline: re-engage deals that went cold 60–90 days ago. And I tighten my ICP so I'm not wasting time on prospects who won't close in this environment." },
      { q: "What's your experience with CRM tools?", category: "Technical", tip: "Be specific about which CRM, how you use it, and what discipline you bring to it.", sample: "I've used Salesforce for 3 years and HubSpot for 1 year. I update activities within 2 hours of every call, keep next steps and close dates current, and run my pipeline review from CRM dashboards — not spreadsheets. Clean data has saved me in every quarterly business review." },
      { q: "How do you build long-term client relationships?", category: "Relationship", tip: "Show post-close discipline — not just 'I stay in touch'.", sample: "I run a 30/60/90 day check-in after every close. I set quarterly business reviews with key accounts and send relevant articles or case studies when I see something useful for their business. I also track their company news so I can congratulate them on wins and show up when they're going through challenges." },
      { q: "How do you manage a large pipeline?", category: "Process", tip: "Show a disciplined, systematic approach — not that you 'just know' what to prioritise.", sample: "I review my full pipeline every Monday morning and categorise deals by: closing this month, next month, and 90 days+. I apply the 'next action, close date, and confidence score' to every deal and eliminate anything I can't name a clear next step for. I'd rather have 20 real deals than 60 fantasy ones." },
    ],
  },
];
