export type Category = {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  bgColor: string;
  borderColor: string;
};

export type Tool = {
  slug: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  featured?: boolean;
  tags: string[];
};

export const categories: Category[] = [
  {
    id: "text",
    name: "Text Tools",
    description: "Word counters, case converters, and more",
    icon: "Type",
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
  },
  {
    id: "math",
    name: "Math & Calculators",
    description: "Calculators for everyday math problems",
    icon: "Calculator",
    color: "text-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
  },
  {
    id: "converters",
    name: "Unit Converters",
    description: "Convert between units instantly",
    icon: "ArrowLeftRight",
    color: "text-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
  },
  {
    id: "finance",
    name: "Finance Tools",
    description: "Loan, interest, and money calculators",
    icon: "TrendingUp",
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
  },
  {
    id: "health",
    name: "Health & Fitness",
    description: "BMI, calorie, and wellness tools",
    icon: "Heart",
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
  },
  {
    id: "developer",
    name: "Developer Tools",
    description: "JSON, Base64, and coding utilities",
    icon: "Code2",
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
  },
  {
    id: "color",
    name: "Color Tools",
    description: "Pick, convert, and explore colors",
    icon: "Palette",
    color: "text-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
  },
  {
    id: "datetime",
    name: "Date & Time",
    description: "Age, duration, and time tools",
    icon: "Clock",
    color: "text-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
  },
  {
    id: "pdf",
    name: "PDF Tools",
    description: "Merge, split, compress, and convert PDFs",
    icon: "FileType",
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
  },
  {
    id: "image",
    name: "Image Tools",
    description: "Compress, resize, and convert images",
    icon: "ImageIcon",
    color: "text-violet-600",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
  },
  {
    id: "office",
    name: "Office Tools",
    description: "Convert Word, Excel, PPT and other office formats",
    icon: "FileBox",
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
  },
  {
    id: "productivity",
    name: "Productivity",
    description: "QR codes, timers, invoices, and everyday utilities",
    icon: "Zap",
    color: "text-emerald-600",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
  },
  {
    id: "utilities",
    name: "Utilities",
    description: "Timezone, base converter, epoch, aspect ratio and more",
    icon: "Wrench",
    color: "text-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
  },
];

export const tools: Tool[] = [
  // Text Tools
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs in your text instantly.",
    category: "text",
    icon: "AlignLeft",
    featured: true,
    tags: ["word count", "character count", "text analysis"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text to UPPERCASE, lowercase, Title Case, camelCase, and more.",
    category: "text",
    icon: "CaseSensitive",
    featured: true,
    tags: ["uppercase", "lowercase", "title case", "camelCase"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for your designs and mockups.",
    category: "text",
    icon: "FileText",
    tags: ["placeholder", "dummy text", "lorem ipsum"],
  },
  {
    slug: "text-reverser",
    name: "Text Reverser",
    description: "Reverse any text, words, or lines with a single click.",
    category: "text",
    icon: "Repeat",
    tags: ["reverse", "flip text", "mirror text"],
  },
  // Math & Calculators
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, discounts, increases, and more with ease.",
    category: "math",
    icon: "Percent",
    featured: true,
    tags: ["percentage", "discount", "percent"],
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Split bills and calculate tips for any group size.",
    category: "math",
    icon: "Receipt",
    featured: true,
    tags: ["tip", "bill split", "restaurant"],
  },
  {
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    description: "A full-featured scientific calculator with memory functions.",
    category: "math",
    icon: "Calculator",
    tags: ["calculator", "math", "scientific"],
  },
  // Unit Converters
  {
    slug: "length-converter",
    name: "Length Converter",
    description: "Convert between meters, feet, inches, kilometers, miles, and more.",
    category: "converters",
    icon: "Ruler",
    featured: true,
    tags: ["length", "distance", "meters", "feet", "miles"],
  },
  {
    slug: "temperature-converter",
    name: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin instantly.",
    category: "converters",
    icon: "Thermometer",
    featured: true,
    tags: ["temperature", "celsius", "fahrenheit", "kelvin"],
  },
  {
    slug: "weight-converter",
    name: "Weight Converter",
    description: "Convert kilograms, pounds, ounces, grams, and more.",
    category: "converters",
    icon: "Scale",
    tags: ["weight", "mass", "kg", "pounds", "grams"],
  },
  // Finance Tools
  {
    slug: "loan-calculator",
    name: "Loan EMI Calculator",
    description: "Calculate monthly EMI payments for loans and mortgages.",
    category: "finance",
    icon: "Landmark",
    featured: true,
    tags: ["loan", "EMI", "mortgage", "interest"],
  },
  {
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    description: "See how your investments grow with the power of compounding.",
    category: "finance",
    icon: "TrendingUp",
    tags: ["compound interest", "investment", "savings"],
  },
  // Health & Fitness
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index and understand your health range.",
    category: "health",
    icon: "Activity",
    featured: true,
    tags: ["BMI", "body mass", "health", "weight"],
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate your exact age in years, months, days, hours, and minutes.",
    category: "health",
    icon: "Cake",
    featured: true,
    tags: ["age", "birthday", "date of birth"],
  },
  {
    slug: "calorie-calculator",
    name: "Calorie Calculator",
    description: "Estimate your daily caloric needs based on your lifestyle.",
    category: "health",
    icon: "Flame",
    tags: ["calories", "diet", "nutrition", "TDEE"],
  },
  // Developer Tools
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data instantly.",
    category: "developer",
    icon: "Braces",
    featured: true,
    tags: ["JSON", "format", "validate", "minify"],
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode or decode text to/from Base64 format instantly.",
    category: "developer",
    icon: "Binary",
    tags: ["Base64", "encode", "decode"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords with custom options.",
    category: "developer",
    icon: "ShieldCheck",
    featured: true,
    tags: ["password", "security", "generator"],
  },
  // Color Tools
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, HSL, and HSV formats.",
    category: "color",
    icon: "Pipette",
    featured: true,
    tags: ["color", "HEX", "RGB", "HSL"],
  },
  // Date & Time
  {
    slug: "date-calculator",
    name: "Date Difference Calculator",
    description: "Find the number of days, weeks, or months between two dates.",
    category: "datetime",
    icon: "CalendarDays",
    featured: true,
    tags: ["date difference", "days between", "calendar"],
  },
  // PDF Tools
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert JPG, PNG, or WebP images into a single PDF. Supports multiple images.",
    category: "pdf",
    icon: "ImageDown",
    featured: true,
    tags: ["image to pdf", "jpg to pdf", "png to pdf", "convert"],
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into a single document in any order.",
    category: "pdf",
    icon: "FilePlus2",
    featured: true,
    tags: ["merge pdf", "combine pdf", "join pdf"],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF into individual pages or extract a custom range of pages.",
    category: "pdf",
    icon: "Scissors",
    featured: true,
    tags: ["split pdf", "extract pages", "separate pdf"],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size by optimizing internal structure and streams.",
    category: "pdf",
    icon: "PackageOpen",
    featured: true,
    tags: ["compress pdf", "reduce pdf size", "optimize pdf"],
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate all or selected pages of a PDF by 90°, 180°, or 270°.",
    category: "pdf",
    icon: "RotateCw",
    tags: ["rotate pdf", "flip pdf", "pdf orientation"],
  },
  {
    slug: "remove-pdf-pages",
    name: "Remove PDF Pages",
    description: "Delete specific pages from a PDF and download the cleaned document.",
    category: "pdf",
    icon: "FileX",
    tags: ["remove pages", "delete pages", "pdf page"],
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add a custom text watermark to every page of your PDF.",
    category: "pdf",
    icon: "Stamp",
    tags: ["watermark pdf", "text watermark", "pdf watermark"],
  },
  {
    slug: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert each page of a PDF into a high-quality PNG image.",
    category: "pdf",
    icon: "FileImage",
    featured: true,
    tags: ["pdf to image", "pdf to png", "pdf to jpg"],
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Draw, type, or upload your signature and embed it into any page of a PDF.",
    category: "pdf",
    icon: "PenLine",
    featured: true,
    tags: ["sign pdf", "pdf signature", "e-sign", "digital signature"],
  },
  {
    slug: "lock-pdf",
    name: "Lock PDF",
    description: "Password-protect a PDF to restrict viewing and editing.",
    category: "pdf",
    icon: "Lock",
    tags: ["lock pdf", "password protect pdf", "encrypt pdf", "secure pdf"],
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove the password from a PDF you own and download it freely.",
    category: "pdf",
    icon: "LockOpen",
    featured: true,
    tags: ["unlock pdf", "remove pdf password", "decrypt pdf"],
  },
  {
    slug: "page-numbers-pdf",
    name: "Add Page Numbers",
    description: "Add page numbers to every page of a PDF with custom position and style.",
    category: "pdf",
    icon: "Hash",
    featured: true,
    tags: ["add page numbers", "pdf page numbers", "number pages"],
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    description: "Trim margins from PDF pages by setting custom crop box dimensions.",
    category: "pdf",
    icon: "Crop",
    tags: ["crop pdf", "trim pdf margins", "pdf crop box"],
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Add text, notes, or annotations on top of any page in your PDF.",
    category: "pdf",
    icon: "FilePen",
    featured: true,
    tags: ["edit pdf", "add text to pdf", "annotate pdf", "pdf editor"],
  },
  {
    slug: "reorder-pdf",
    name: "Reorder PDF Pages",
    description: "Rearrange the pages of a PDF into any order you choose.",
    category: "pdf",
    icon: "ListOrdered",
    tags: ["reorder pdf pages", "rearrange pdf", "sort pdf pages"],
  },
  {
    slug: "header-footer-pdf",
    name: "Header & Footer",
    description: "Add custom header and footer text to every page of a PDF.",
    category: "pdf",
    icon: "AlignVerticalSpaceBetween",
    tags: ["pdf header footer", "add header pdf", "add footer pdf"],
  },
  {
    slug: "flatten-pdf",
    name: "Flatten PDF",
    description: "Flatten form fields and annotations into static content so they cannot be edited.",
    category: "pdf",
    icon: "Layers",
    tags: ["flatten pdf", "pdf form flatten", "remove form fields pdf"],
  },
  {
    slug: "grayscale-pdf",
    name: "PDF to Grayscale",
    description: "Convert a color PDF to black-and-white (grayscale) for printing or archiving.",
    category: "pdf",
    icon: "Circle",
    tags: ["grayscale pdf", "black and white pdf", "pdf to bw", "pdf color to grayscale"],
  },
  // Image Tools
  {
    slug: "compress-image",
    name: "Compress Image",
    description: "Compress JPG or PNG images to a smaller file size with quality control.",
    category: "image",
    icon: "Minimize2",
    featured: true,
    tags: ["compress image", "reduce image size", "optimize image", "jpg compress"],
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    description: "Resize images to exact pixel dimensions while optionally keeping aspect ratio.",
    category: "image",
    icon: "Maximize2",
    featured: true,
    tags: ["resize image", "image dimensions", "scale image"],
  },
  {
    slug: "convert-image",
    name: "Convert Image Format",
    description: "Convert images between JPG, PNG, and WebP formats instantly in your browser.",
    category: "image",
    icon: "RefreshCw",
    tags: ["convert image", "jpg to png", "png to webp", "image format"],
  },
  {
    slug: "flip-image",
    name: "Flip & Rotate Image",
    description: "Flip an image horizontally or vertically, or rotate it by 90°, 180°, or 270°.",
    category: "image",
    icon: "FlipHorizontal",
    tags: ["flip image", "rotate image", "mirror image"],
  },
  // Office Tools
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert .docx Word documents to PDF directly in your browser.",
    category: "office",
    icon: "FileOutput",
    featured: true,
    tags: ["word to pdf", "docx to pdf", "convert word", "office"],
  },
  {
    slug: "word-to-text",
    name: "Word to Text",
    description: "Extract plain text from any .docx Word document instantly.",
    category: "office",
    icon: "FileType2",
    tags: ["word to text", "docx to txt", "extract text", "word"],
  },
  {
    slug: "excel-to-csv",
    name: "Excel to CSV",
    description: "Convert .xlsx or .xls Excel spreadsheets to CSV format.",
    category: "office",
    icon: "Table2",
    featured: true,
    tags: ["excel to csv", "xlsx to csv", "spreadsheet", "convert excel"],
  },
  {
    slug: "csv-to-excel",
    name: "CSV to Excel",
    description: "Convert a CSV file into a properly formatted .xlsx Excel spreadsheet.",
    category: "office",
    icon: "Sheet",
    tags: ["csv to excel", "csv to xlsx", "spreadsheet", "convert csv"],
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert Excel spreadsheets (.xlsx) to a PDF document.",
    category: "office",
    icon: "FileSpreadsheet",
    tags: ["excel to pdf", "xlsx to pdf", "spreadsheet to pdf"],
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract all readable text from a PDF and download it as a .txt file.",
    category: "office",
    icon: "FileSearch",
    featured: true,
    tags: ["pdf to text", "extract text from pdf", "pdf text"],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Extract content from a PDF and download it as an editable Word-compatible .rtf file.",
    category: "office",
    icon: "FileInput",
    tags: ["pdf to word", "pdf to docx", "pdf to rtf", "convert pdf"],
  },
  {
    slug: "ppt-to-pdf",
    name: "PowerPoint to PDF",
    description: "Convert .pptx PowerPoint presentations to PDF. (Coming soon — requires server-side rendering)",
    category: "office",
    icon: "PresentationIcon",
    tags: ["ppt to pdf", "pptx to pdf", "powerpoint", "presentation"],
  },
  // Text Tools — new
  {
    slug: "text-diff",
    name: "Text Diff Checker",
    description: "Compare two texts side by side and highlight additions and deletions.",
    category: "text",
    icon: "GitCompare",
    featured: true,
    tags: ["diff", "compare text", "text difference", "find changes"],
  },
  {
    slug: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    description: "Paste a list and instantly remove all duplicate lines.",
    category: "text",
    icon: "ListFilter",
    tags: ["duplicate lines", "remove duplicates", "unique lines", "clean list"],
  },
  {
    slug: "text-to-slug",
    name: "Text to Slug",
    description: "Convert any title or phrase into a clean URL-friendly slug.",
    category: "text",
    icon: "Link",
    tags: ["slug", "url slug", "permalink", "seo url"],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write Markdown on the left and see a live HTML preview on the right.",
    category: "text",
    icon: "FileCode",
    featured: true,
    tags: ["markdown", "preview", "markdown editor", "md to html"],
  },
  {
    slug: "find-replace",
    name: "Find & Replace",
    description: "Find and replace words or phrases in any block of text instantly.",
    category: "text",
    icon: "Replace",
    tags: ["find replace", "text replace", "search replace", "substitute"],
  },
  {
    slug: "remove-extra-spaces",
    name: "Remove Extra Spaces",
    description: "Clean up extra spaces, blank lines, and whitespace from any text.",
    category: "text",
    icon: "RemoveFormatting",
    tags: ["remove spaces", "clean text", "trim whitespace", "remove blank lines"],
  },
  // Math — new
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    description: "Calculate GST-inclusive or GST-exclusive price for any tax rate.",
    category: "math",
    icon: "Receipt",
    featured: true,
    tags: ["gst", "vat", "tax calculator", "gst inclusive", "gst exclusive"],
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    description: "Find the final price after applying a percentage or flat discount.",
    category: "math",
    icon: "Tag",
    featured: true,
    tags: ["discount", "sale price", "percentage off", "coupon"],
  },
  {
    slug: "fuel-cost-calculator",
    name: "Fuel Cost Calculator",
    description: "Estimate the total fuel cost for a trip based on distance and mileage.",
    category: "math",
    icon: "Fuel",
    tags: ["fuel cost", "petrol cost", "trip cost", "mileage calculator"],
  },
  {
    slug: "roman-numeral",
    name: "Roman Numeral Converter",
    description: "Convert numbers to Roman numerals and Roman numerals back to numbers.",
    category: "math",
    icon: "LetterText",
    tags: ["roman numerals", "roman numeral converter", "numbers to roman"],
  },
  // Finance — new
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    description: "Calculate the maturity value of your monthly SIP investments over time.",
    category: "finance",
    icon: "PiggyBank",
    featured: true,
    tags: ["sip", "mutual fund", "investment calculator", "monthly investment"],
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    description: "Convert amounts between 30+ world currencies using live exchange rates.",
    category: "finance",
    icon: "DollarSign",
    featured: true,
    tags: ["currency converter", "exchange rate", "forex", "usd inr", "convert currency"],
  },
  {
    slug: "salary-calculator",
    name: "Salary / CTC Calculator",
    description: "Break down your CTC into take-home salary, HRA, PF, and deductions.",
    category: "finance",
    icon: "Briefcase",
    featured: true,
    tags: ["salary calculator", "ctc calculator", "take home salary", "in-hand salary"],
  },
  {
    slug: "fd-calculator",
    name: "FD / RD Calculator",
    description: "Calculate the maturity amount for Fixed Deposits and Recurring Deposits.",
    category: "finance",
    icon: "Banknote",
    tags: ["fd calculator", "rd calculator", "fixed deposit", "recurring deposit"],
  },
  // Health — new
  {
    slug: "water-intake",
    name: "Water Intake Calculator",
    description: "Find out how much water you should drink daily based on your weight and activity.",
    category: "health",
    icon: "GlassWater",
    tags: ["water intake", "hydration", "daily water", "drink water"],
  },
  {
    slug: "sleep-calculator",
    name: "Sleep Calculator",
    description: "Find the best times to wake up or go to sleep based on 90-minute sleep cycles.",
    category: "health",
    icon: "Moon",
    featured: true,
    tags: ["sleep calculator", "wake up time", "sleep cycles", "bedtime"],
  },
  {
    slug: "ideal-weight",
    name: "Ideal Weight Calculator",
    description: "Calculate your ideal body weight range based on height and gender.",
    category: "health",
    icon: "Weight",
    tags: ["ideal weight", "healthy weight", "body weight", "weight range"],
  },
  {
    slug: "pregnancy-calculator",
    name: "Pregnancy Due Date",
    description: "Calculate your expected due date and current week of pregnancy.",
    category: "health",
    icon: "Baby",
    featured: true,
    tags: ["pregnancy calculator", "due date", "edd", "weeks pregnant"],
  },
  {
    slug: "heart-rate-zones",
    name: "Heart Rate Zones",
    description: "Calculate your target heart rate zones for fat burn, cardio, and peak training.",
    category: "health",
    icon: "HeartPulse",
    tags: ["heart rate zones", "target heart rate", "cardio zones", "fat burn zone"],
  },
  // Developer Tools — new
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode special characters in a URL or decode an encoded URL string.",
    category: "developer",
    icon: "Link2",
    featured: true,
    tags: ["url encoder", "url decoder", "encode url", "percent encoding"],
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities like &amp;, &lt;, &gt; and more.",
    category: "developer",
    icon: "Code",
    tags: ["html entities", "html encode", "html decode", "escape html"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect the header, payload, and expiry of any JWT token.",
    category: "developer",
    icon: "Key",
    featured: true,
    tags: ["jwt", "jwt decoder", "json web token", "token decoder"],
  },
  {
    slug: "cron-builder",
    name: "Cron Expression Builder",
    description: "Build, validate, and understand cron schedule expressions visually.",
    category: "developer",
    icon: "AlarmClock",
    tags: ["cron", "cron expression", "cron builder", "cron scheduler"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions against any text with live match highlighting.",
    category: "developer",
    icon: "Search",
    featured: true,
    tags: ["regex", "regular expression", "regex tester", "regexp"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate one or many random UUIDs (v4) with a single click.",
    category: "developer",
    icon: "Fingerprint",
    tags: ["uuid", "guid", "uuid generator", "unique id"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from any text.",
    category: "developer",
    icon: "ShieldCheck",
    featured: true,
    tags: ["hash", "sha256", "md5", "sha1", "checksum", "hash generator"],
  },
  {
    slug: "ip-lookup",
    name: "IP Address Lookup",
    description: "Find your public IP address and see its country, city, and ISP info.",
    category: "developer",
    icon: "Globe",
    tags: ["ip lookup", "my ip address", "ip location", "what is my ip"],
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier / Beautifier",
    description: "Minify bloated CSS or beautify minified CSS back into readable form.",
    category: "developer",
    icon: "Braces",
    tags: ["css minifier", "css beautifier", "minify css", "format css"],
  },
  // Image Tools — new
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop any image to exact pixel dimensions or a custom aspect ratio.",
    category: "image",
    icon: "Crop",
    featured: true,
    tags: ["crop image", "image cropper", "trim image", "cut image"],
  },
  {
    slug: "watermark-image",
    name: "Watermark Image",
    description: "Add a custom text watermark to any image with control over position and opacity.",
    category: "image",
    icon: "Stamp",
    tags: ["watermark image", "add watermark", "image watermark", "text watermark"],
  },
  {
    slug: "image-color-picker",
    name: "Image Color Picker",
    description: "Upload an image and click any pixel to pick its exact HEX and RGB color.",
    category: "image",
    icon: "Pipette",
    featured: true,
    tags: ["color picker", "pick color from image", "eyedropper", "image color"],
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert any image to a Base64-encoded string for use in HTML or CSS.",
    category: "image",
    icon: "FileImage",
    tags: ["image to base64", "base64 image", "encode image", "data url"],
  },
  // Productivity (new category)
  {
    slug: "ats-score",
    name: "ATS Resume Scorer",
    description: "Upload your resume and paste a job description to get an ATS compatibility score with keyword analysis and tips.",
    category: "productivity",
    icon: "FileSearch",
    featured: true,
    tags: ["ats score", "resume checker", "ats resume", "resume scanner", "job application", "keyword match"],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate a QR code for any URL, text, email, or phone number instantly.",
    category: "productivity",
    icon: "QrCode",
    featured: true,
    tags: ["qr code", "qr generator", "qr code maker", "barcode"],
  },
  {
    slug: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Stay focused with 25-minute work sessions and 5-minute breaks.",
    category: "productivity",
    icon: "Timer",
    featured: true,
    tags: ["pomodoro", "focus timer", "productivity timer", "25 minute timer"],
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    description: "Set a custom countdown timer with an alarm and a visual progress ring.",
    category: "productivity",
    icon: "Hourglass",
    tags: ["countdown timer", "timer", "alarm", "stopwatch"],
  },
  {
    slug: "random-number",
    name: "Random Number Generator",
    description: "Generate random numbers within any range, with optional unique values.",
    category: "productivity",
    icon: "Dice5",
    tags: ["random number", "random generator", "dice roller", "number generator"],
  },
  {
    slug: "coin-flip",
    name: "Coin Flip & Dice Roller",
    description: "Flip a virtual coin or roll up to 6 dice with animated results.",
    category: "productivity",
    icon: "CircleDot",
    tags: ["coin flip", "dice roller", "flip coin", "roll dice"],
  },
  {
    slug: "reading-time",
    name: "Reading Time Estimator",
    description: "Paste any text to instantly see how long it takes to read at average speed.",
    category: "productivity",
    icon: "BookOpen",
    tags: ["reading time", "read time", "minutes to read", "reading speed"],
  },
  {
    slug: "character-limit",
    name: "Character Limit Checker",
    description: "Check your text length against Twitter, LinkedIn, SMS, and meta tag limits.",
    category: "productivity",
    icon: "TextCursorInput",
    tags: ["character limit", "character counter", "twitter limit", "sms limit"],
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    description: "Create and download a professional PDF invoice in seconds — no sign-up.",
    category: "productivity",
    icon: "FileText",
    featured: true,
    tags: ["invoice generator", "create invoice", "pdf invoice", "freelance invoice"],
  },
  {
    slug: "typing-speed-test",
    name: "Typing Speed Test",
    description: "Test your typing speed in WPM and accuracy. Choose easy, medium, or hard difficulty and beat your score.",
    category: "productivity",
    icon: "Keyboard",
    featured: true,
    tags: ["typing speed test", "wpm", "typing test", "words per minute", "keyboard speed"],
  },
  // Utilities (new category)
  {
    slug: "timezone-converter",
    name: "Timezone Converter",
    description: "Convert a time from one timezone to another across major world cities.",
    category: "utilities",
    icon: "Globe2",
    featured: true,
    tags: ["timezone converter", "time zone", "world time", "convert timezone"],
  },
  {
    slug: "aspect-ratio",
    name: "Aspect Ratio Calculator",
    description: "Calculate equivalent dimensions while maintaining a specific aspect ratio.",
    category: "utilities",
    icon: "RectangleHorizontal",
    tags: ["aspect ratio", "image dimensions", "ratio calculator", "16:9"],
  },
  {
    slug: "readability-score",
    name: "Readability Score",
    description: "Measure the reading ease of your text using the Flesch-Kincaid formula.",
    category: "utilities",
    icon: "BarChart2",
    tags: ["readability", "flesch kincaid", "reading level", "reading ease"],
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hexadecimal bases.",
    category: "utilities",
    icon: "Binary",
    featured: true,
    tags: ["binary converter", "hex converter", "octal", "number base", "decimal to binary"],
  },
  {
    slug: "epoch-converter",
    name: "Epoch / Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates and vice versa.",
    category: "utilities",
    icon: "Clock3",
    featured: true,
    tags: ["epoch", "unix timestamp", "timestamp converter", "epoch to date"],
  },
  // New trending tools
  {
    slug: "ai-prompt-generator",
    name: "AI Prompt Generator",
    description: "Generate powerful prompts for ChatGPT, Claude, Midjourney, DALL·E, and more with custom tone, format, and style.",
    category: "productivity",
    icon: "Wand2",
    featured: true,
    tags: ["ai prompt", "chatgpt prompt", "midjourney prompt", "prompt generator", "ai prompt writer"],
  },
  {
    slug: "grammar-checker",
    name: "Grammar Checker",
    description: "Check your text for grammar errors, passive voice, weak words, and style issues — free, no sign-up.",
    category: "text",
    icon: "SpellCheck",
    featured: true,
    tags: ["grammar checker", "grammar check", "spell check", "grammar tool", "free grammar checker", "grammarly alternative"],
  },
  {
    slug: "plagiarism-checker",
    name: "Plagiarism Checker",
    description: "Compare two texts and detect similarity, matching sentences, and shared content percentage instantly.",
    category: "text",
    icon: "ScanText",
    featured: true,
    tags: ["plagiarism checker", "similarity checker", "plagiarism detector", "text similarity", "duplicate content checker"],
  },
  {
    slug: "tax-regime-calculator",
    name: "Old vs New Tax Regime Calculator",
    description: "Compare Old and New Income Tax Regime for FY 2025-26. See which regime saves you more tax with a detailed breakdown.",
    category: "finance",
    icon: "IndianRupee",
    featured: true,
    tags: ["tax regime calculator", "old vs new tax regime", "income tax calculator india", "tax calculator 2025-26", "new tax regime", "tax saving"],
  },
  {
    slug: "cgpa-calculator",
    name: "CGPA to Percentage Calculator",
    description: "Convert CGPA to percentage using multiple university formulas including Anna University × 9.5 scale.",
    category: "math",
    icon: "GraduationCap",
    featured: true,
    tags: ["cgpa to percentage", "cgpa calculator", "anna university", "grade conversion", "cgpa percentage"],
  },
  {
    slug: "loan-eligibility",
    name: "Loan Eligibility Calculator",
    description: "Find out how much home loan or personal loan you are eligible for based on your income and expenses.",
    category: "finance",
    icon: "Banknote",
    featured: true,
    tags: ["loan eligibility", "home loan eligibility", "personal loan", "loan amount calculator", "bank loan"],
  },
  {
    slug: "notice-period-calculator",
    name: "Notice Period Calculator",
    description: "Calculate your last working day and notice period buyout cost based on your resignation date.",
    category: "productivity",
    icon: "CalendarClock",
    featured: true,
    tags: ["notice period calculator", "last working day", "resignation", "notice buyout", "notice period"],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter((t) => t.category === categoryId);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((t) => t.featured);
}

const POPULAR_TOOL_SLUGS = [
  "ats-score",
  "merge-pdf",
  "compress-pdf",
  "image-to-pdf",
  "word-to-pdf",
  "qr-code-generator",
  "compress-image",
  "bmi-calculator",
  "currency-converter",
];

export function getPopularTools(): Tool[] {
  return POPULAR_TOOL_SLUGS
    .map((slug) => tools.find((t) => t.slug === slug))
    .filter((t): t is Tool => t !== undefined);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase();
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q))
  );
}
